### ISSUE TITLE
Armf/arm64 support

### ISSUE THREAD

**Issue by NoxInmortus** [ollm/OpenComic#10]
Hello, 

I liked your work, but after trying to install your project on a arm64 virtual instance, I realized it doesn't seems to support armf or arm64 architectures.

It could be great tho, this kind of project could fit perfectly on a mini-machine, a raspberrypi or a arm64 virtual instance.

Do you have any plans supporting theses plateforms ?

**Comment by ollm** [comment]
I just added the arm64 binaries in the release.

A greeting.

###### Release
* https://github.com/ollm/OpenComic/releases/tag/v0.1.2

###### Linux Arm64
* [arm64.deb](https://github.com/ollm/OpenComic/releases/download/v0.1.2/opencomic_0.1.2_arm64.deb)
* [arm64.rpm](https://github.com/ollm/OpenComic/releases/download/v0.1.2/opencomic-0.1.2.arm64.rpm)
* [arm64.tar.gz](https://github.com/ollm/OpenComic/releases/download/v0.1.2/opencomic-0.1.2-arm64.tar.gz)
