### ISSUE TITLE
[Feature request] Sync chapters after reading, search bar etc..

### ISSUE THREAD

**Issue by TheFermi0n** [ollm/OpenComic#102]
- Instead of syncing a chapter immediatly with anilist it should update anilist after I have completed the chapter. [Atleast make add an option to do this.]
- Add a search bar so that i can direcly go to that chapter instead of scrolling through the manga.
- i don't know why preview images are not showing at all. [if you may fix this too]

**Comment by Razi1660** [comment]
+1 to this, it would be nice if it would update anilist after finishing a chapter rather than at the start

**Comment by VaryVI** [comment]
anilist syncing? that sounds annoying tbh. if i go back and reread chapter 1 would my anilist tracking go back to 1? i'd rather just use anilist manually, and just update the number of chapters read and the end of a reading session. it's not that hard, doesn't take too long.

**Comment by ollm** [comment]
> Instead of syncing a chapter immediatly with anilist it should update anilist after I have completed the chapter. [Atleast make add an option to do this.]

Closed as completed in 39f19546b2fd363d321f9c423e706c3dc773aa4f and available in [v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3)

> Add a search bar so that i can direcly go to that chapter instead of scrolling through the manga.

Support of search bar and filter bar 8393903117981bea2b8a79e2e50b77d02334aa05 also available in in [v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3)

> i don't know why preview images are not showing at all. [if you may fix this too]

In v1.0.0-beta.1 all the code for file management has been rewritten, this should be fixed now c1259bb512983751fe41304c7c642966b204aea1

Feel free to comment if you find any bugs.
