### ISSUE TITLE
[Feature request] Add global zoom level for reader

### ISSUE THREAD

**Issue by heybbygurl** [ollm/OpenComic#103]
Currently as it is, zoom only works by a page-by-page basis and resets when scrolling/changing the page.
There is also the issue of not being able to view the page at its original size, either shrinking or stretching it to fit.

Add a setting to change the zoom level for the entire reader with user specified values for zoom change step and default viewer zoom.
Something similar to https://github.com/TagoDR/MangaOnlineViewer

**Comment by VEGEMITEGOD** [comment]
Honestly, I 100% agree. At the moment, this is the only feature I feel is missing from OpenComic before I can use it for all my Manga/Webtoon/Doujin needs.

**Comment by a-zaghloul** [comment]
Agreed, I was surprised OpenComic can not already do this.

**Comment by a-zaghloul** [comment]
Agreed, I was a bit surprised that OpenComic can not already do this.

**Comment by kamikazilucas** [comment]
please can someone add this the pages are too small rn

**Comment by raffle2** [comment]
I would also love this, it's literally the one feature preventing me from using this over cdisplayex :(

**Comment by topotech** [comment]
Seconding this. it's particularly important for vertical scrolling comics, since resizing one page breaks the continuity.

**Comment by ollm** [comment]
Implemented it in c94ac75d5f247a1f423b4192d1b1cab2c066be6f

It still has some bugs, but it's mostly functional
