### ISSUE TITLE
add cover support

### ISSUE THREAD

**Issue by Robonau** [ollm/OpenComic#105]
ideally in the same way komga does
https://komga.org/guides/local-artwork-assets.html#poster-artwork
as I and I'm sure other possible users of this will also use komga and may already have covers setup for series folders and chapters/volumes

**Comment by ollm** [comment]
Closed as completed in f774ed41eaa459c69f1b7d5a9f82ef83c067ceb2 and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.
