### ISSUE TITLE
[Feature request] AVIF/HEIF support...

### ISSUE THREAD

**Issue by paconaranjo** [ollm/OpenComic#109]
Please add at least AVIF, is the best image (quality/size) format for comics.
![Image comparison](https://user-images.githubusercontent.com/719690/130724140-27d37516-0cef-45f0-a65a-087c6f95d90c.png)

**Comment by ollm** [comment]
I have added AVIF support https://github.com/ollm/OpenComic/commit/8a0d2741793598f3728a52ba1e24f90c34100375, I can't add HEIF support at the moment until Chromium supports it.

**Comment by ollm** [comment]
Here is the compile version for Windows with AVIF support https://mega.nz/file/DSZCTZYA#Zk2TDM_wfS1RbH-30qDP-oknMQaH7hllb4N92oHGnY4

**Comment by paconaranjo** [comment]
Thanks, now I can see AVIF files with OpenComic, but are blurry. If you compare que image open with XnView MP with the one open with OpenComic you can see the difference. Even all other images (png, jpg, etc...) are blurry in OpenComic.
![1](https://user-images.githubusercontent.com/719690/131232632-45e16c3a-a855-4eae-9bee-dc24e606b945.png)
![2](https://user-images.githubusercontent.com/719690/131232636-da360792-0656-4c76-9012-b9558ab14d6b.png)

**Comment by ollm** [comment]
It seems that when zooming it looks blurry, I have already corrected this in 23bcb873bed33e1085fc39e7b4018d75465a5f01

https://mega.nz/file/XfpxUSKZ#xc14bybCZLitbr_jbV7zBhnLdgmerIL5-KMS71KrIyo

**Comment by paconaranjo** [comment]
Much better! Thanks.
