### ISSUE TITLE
What about a Mac Release?

### ISSUE THREAD

**Issue by mustii82** [ollm/OpenComic#11]
What about a Mac Release?

**Comment by ollm** [comment]
I do not have a macOS device available, so I can not build dmg or pkg, the only thing I could do is distribute the application in a zip or tar.gz with the packaging for macOS.

**Comment by ollm** [comment]
I posted a release with the zip and tar.gz for macOS.

https://github.com/ollm/OpenComic/releases/tag/v0.1.3
