### ISSUE TITLE
navigate around with keyboard

### ISSUE THREAD

**Issue by hpn33** [ollm/OpenComic#113]
for explore on comic list
exit from open comic

and show the shortcut key on tooltip

thanks

**Comment by ollm** [comment]
Closed as completed in 922e6ee0fe1509f2dfae0003406e24ce26aa49fb and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.
