### ISSUE TITLE
Bigger horizontal margin

### ISSUE THREAD

**Issue by xbowzone** [ollm/OpenComic#120]
Hello, I'd like to request to provide option of bigger horizontal margin in the future update. More than current 200

**Comment by VaryVI** [comment]
i was wanting the same thing

**Comment by VaryVI** [comment]
same here, i want a margin of at least 600.

**Comment by VaryVI** [comment]
i's also like this, the margin i want is 600, but more wouldn't hurt.

**Comment by Darkmaster006** [comment]
This is definitely necessary, especially for webtoons.

**Comment by ollm** [comment]
Implemented it in f2de2d26ef55ed0f4b9146caefc89e590198b403
