### ISSUE TITLE
Continue reading more than 1 comic?

### ISSUE THREAD

**Issue by kot7k** [ollm/OpenComic#122]
Hi,
I just discovered this and i'm liking it a lot but could be possible for the software to save the position you are reading in more than one comic/folder? example:
-You start reading comic A to chapter 7 page 10 .
-You start reading comic B to chapter 2 page 5.

You close the app, reopen the app and the app tells you that you could continue comic A from  chapter 7 page 10 or comic B chapter 2 page 5.

**Comment by kot7k** [comment]
My bad i just added a folder contaning more folders inside and it doesnt work this way. I should add the subfolders with the comics instead of 1 big folder and it works like i expected.

**Comment by ollm** [comment]
Hi @kot7k, now you can use master folders to have all the content in the library without having to add it every time in. 

Matser folders: https://github.com/ollm/OpenComic/blob/master/SCREENSHOTS.MD#master-folders
Latest beta version: [v1.0.0-beta.5](https://github.com/ollm/OpenComic/releases)
