### ISSUE TITLE
Please add an option to display images in their original width

### ISSUE THREAD

**Issue by meidoqt** [ollm/OpenComic#123]
That's all, thank you

**Comment by VaryVI** [comment]
that would be nice

**Comment by dajotim937** [comment]
Hi. Is it possible to set original size of images as default view? I set in settings global zoom, opened file, set original size of image, then opened next file and it didn't save "original size".

**Comment by ollm** [comment]
> Hi. Is it possible to set original size of images as default view? I set in settings global zoom, opened file, set original size of image, then opened next file and it didn't save "original size".

Currently no, it is only possible to maintain the current zoom applied when changing pages, which if it is the original size of the image (Reset zoom/original size button) will be maintained in the following ones (If they have the same size)

I have opened a new issue as a feature request for this #182

https://github.com/ollm/OpenComic/assets/18549191/e7de967c-2fee-473b-9e54-5aa8dd8ba784
