### ISSUE TITLE
why dont have key shortcut?

### ISSUE THREAD

**Issue by B0yEditi0n** [ollm/OpenComic#124]
hello guys, i like this app but active the magnifying glass with a key in keybord may be help a lot, if one day the developers decide to insert keyboard shortcuts please let me know.
Thanks

**Comment by ollm** [comment]
Closed as completed in 0a4a4597883c7c6c837acdd61e4d80dc8c0a0ec1 and available in [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2)

If you are missing any default shortcuts or any configurable action, open a new issue and I will try to add it for the next version.
