### ISSUE TITLE
can't unzip!?

### ISSUE THREAD

**Issue by sohyuung** [ollm/OpenComic#125]
why this happening? the file does open from another app
![Screenshot (46)](https://user-images.githubusercontent.com/84577855/145661816-a65fd75c-ce99-43cb-a0b4-dd6b48b37659.png)

**Comment by ollm** [comment]
This is probably fixed in the beta version [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.
