### ISSUE TITLE
OpenComic portable version

### ISSUE THREAD

**Issue by JamesJacquesDiego** [ollm/OpenComic#126]
Hi,
The OpenComic app is great, but I miss the portable version for Windows. Is there a chance to add the portable version?

**Comment by JamesJacquesDiego** [comment]
Is it possible?

**Comment by hormoz1** [comment]
Just create an exe yourself from the source if you really want one.

**Comment by JamesJacquesDiego** [comment]
Could you tell me how to create an exe from the source? If I create such exe, the app will be portable (all files will be stored in one place?

**Comment by hormoz1** [comment]
To begin with, you don't need it to be an exe to run it, you can simply run it from source. Look at this section on how to simply start it:
https://github.com/ollm/OpenComic#installation-and-starting-for-development
--------------
If you want to make an exe, then simply use something like electron-builder.

**Comment by JamesJacquesDiego** [comment]
Thank you for your explanation. To use npm like that I should install node.js? 
It would be great if you could add the portable version. I've tried many apps to read comics but yours is the best :)

**Comment by ollm** [comment]
> Thank you for your explanation. To use npm like that I should install node.js?

Yes, also you need to install [git](https://git-scm.com/) for clone the repository.

**Comment by ollm** [comment]
Now the portable version is available in beta version [v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3)
