### ISSUE TITLE
Distribute OpenComic in a Flatpak

### ISSUE THREAD

**Issue by LeandroStanger** [ollm/OpenComic#13]
http://docs.flatpak.org/en/latest/introduction.html#reasons-to-use-flatpak
https://github.com/flathub/flathub/wiki/App-Submission

**Comment by ollm** [comment]
For the build i use [electron-builder](https://github.com/electron-userland/electron-builder), currently [electron-builder](https://github.com/electron-userland/electron-builder) is not compatible with Flatpack:  electron-userland/electron-builder#512

When [electron-builder](https://github.com/electron-userland/electron-builder) supports Flatpack, i will try to add the build

A greeting.

**Comment by ollm** [comment]
Now the Flatpack package is available in beta version [v1.0.0-beta.4](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.4)

When I publish the final 1.0.0 version I will submit it to Flathub.

**Comment by nvllsvm** [comment]
Is this still going to get added to Flathub?
