### ISSUE TITLE
Bigger Horizontal Margins

### ISSUE THREAD

**Issue by Darkmaster006** [ollm/OpenComic#131]
Especially for reading webtoons, there's a need for bigger horizontal margins, why not set it to unlimited? Otherwise the image is still too big to see it correctly. I hope this can be implemented, thank you.

**Comment by ollm** [comment]
Implemented it in f2de2d26ef55ed0f4b9146caefc89e590198b403

**Comment by Darkmaster006** [comment]
> Implemented it in [f2de2d2](https://github.com/ollm/OpenComic/commit/f2de2d26ef55ed0f4b9146caefc89e590198b403)

Thank you for implementing it!! I'm eager to use it. Is there a way to download an "unstable" version or should we wait for a newer release? Thank you.

**Comment by ollm** [comment]
Later I can build a beta version for windows, but you can also build following the next instructions.

__Requirements__: Git, Node and NPM

```
git clone https://github.com/ollm/OpenComic.git
cd OpenComic
npm install
npm install --only=dev
npm run rebuild
```
And build for windows
```
npm run build-nsis
```

If the build goes well, it will appear a `exe` file inner the `dist` folder

**Comment by Darkmaster006** [comment]
> I leave you a build for windows with these changes
> 
> https://mega.nz/file/nKJRTCgY#lztR_fRpAttCsJ5NW80Xn1iR4oX61JJZruzr-6ctx_Q

Thank you very much for both the instructions and the link!
