### ISSUE TITLE
Delay in changing comics cannoy be set to 0.0s

### ISSUE THREAD

**Issue by Darkmaster006** [ollm/OpenComic#132]
Delay in changing comics cannoy be set to 0.0s, this cannot be done, if you do it, it just goes back without telling you.

**Comment by ollm** [comment]
Fixed in f0a65e8781d128241215203ab0863cb32193d6c2

**Comment by Darkmaster006** [comment]
> Fixed in [f0a65e8](https://github.com/ollm/OpenComic/commit/f0a65e8781d128241215203ab0863cb32193d6c2)

Thank you very much!
