### ISSUE TITLE
Keyboard shortcuts?

### ISSUE THREAD

**Issue by Darkmaster006** [ollm/OpenComic#133]
Are there any keyboard shortcuts for hiding the side pane, the top bar and other stuff? Thanks.

**Comment by ollm** [comment]
Closed as completed in 0a4a4597883c7c6c837acdd61e4d80dc8c0a0ec1 and available in [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2)

If you are missing any default shortcuts or any configurable action, open a new issue and I will try to add it for the next version.
