### ISSUE TITLE
Zoom with low quality and big images (and proposed solution)

### ISSUE THREAD

**Issue by topotech** [ollm/OpenComic#135]
Hi! First of all, thanks a lot for this program, it really helped with webtoon-like comics on desktop.

Recently I tried to use OpenComic to read traditional horizontal comics instead (and take advantage of its "scroll to zoom" feature) but I noticed that regardless of the resolution of the pages, the zoom blurred the images a lot:
 
Normal:
![imagen](https://user-images.githubusercontent.com/8272252/163094645-0aaccd38-63fd-40bd-b12f-5a44a3d3eb96.png)

Zoomed:
![imagen](https://user-images.githubusercontent.com/8272252/163094700-d68f864a-596b-4732-82d8-3e7ffe122a83.png)

Messing with the devtools, I realized that the problem was the double-resizing: In order to set the margins, you set the image style (nested in a `r-img` class `div`). That's fine, but then to zoom what gets transformed is the parent `r-flex` class `div`, so what gets zoomed is an already shrunken image, hence the blur. In other words: _the bigger the image, the worse is the blur_.

![imagen](https://user-images.githubusercontent.com/8272252/163097306-45c34509-651e-4651-8da7-f6e3f56f0d47.png)

Well, I'm not sure why (I read [the documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/will-change) but I couldn't understand why this works), but overriding the `will-change` property of _all_ the `r-flex` divs from `transform` to `auto`, forces the reader to re-render the image after the transformation.

![imagen](https://user-images.githubusercontent.com/8272252/163096425-42089c19-0ded-4d65-a356-419386e2e692.png) 
![imagen](https://user-images.githubusercontent.com/8272252/163097249-c1551ca1-2d57-443d-9ea0-52a3b3b63fa1.png)

This was tested on Manjaro Linux, built from the [updated package](https://aur.archlinux.org/packages/opencomic-bin) in the AUR repository.

**Comment by salazarbarrera** [comment]
Did this ever arrive to the stable release? I've been using for some time a custom version, but now that I moved to a new machine I installed the Snap version and it still has the old CSS.
