### ISSUE TITLE
Quality is poor with cbz format and jpg

### ISSUE THREAD

**Issue by Glonko8** [ollm/OpenComic#140]
Opencomic is the the top
Yacreader is the bottom
this is in cbz format but the problem insists on jpg format

![Capture](https://user-images.githubusercontent.com/104344152/173201160-20588072-b63c-47df-8faa-21a0bbdbaf41.PNG)
![Capture1](https://user-images.githubusercontent.com/104344152/173201164-7adb41e6-db9b-43a7-91b9-abe07c194e93.PNG)

**Comment by Glonko8** [comment]
also when i go full screen the quality improves slightly on opencomic but is still noticeably worse

**Comment by ollm** [comment]
Probably it's the same bug as #135 #136 

Can you test if the changes in #136 fix it?

**Comment by ollm** [comment]
Closed as completed and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.
