### ISSUE TITLE
Can't open files/folders with unusual characters

### ISSUE THREAD

**Issue by JoePalffy** [ollm/OpenComic#142]
To keep my stuff organized i use special characters like • (Alt+7) in my folder names and OpenComic cannot read anything in any of it's subfolders, so I either would have to rename the main folder to accommodate OpenComic or stick to the 2 other CBZ comic readers i have that have no problem with such characters.
See screenshot below of the error message it gives.
<img width="418" alt="2022-06-17 03_07_01-Linenumber 1057_28" src="https://user-images.githubusercontent.com/14361452/174197819-f433678c-d5b4-40b0-bcbb-b07b47e7326f.png">
(i only used this app for 5 seconds and already there is a deal-breaker issue)
I'm using the latest 0.2.1 version on Win 10 64bit.
.

**Comment by ollm** [comment]
Probably fixed in 5499e39a3a026b636cdf9bf907d47ba3d4f5ca64

I leave you a version with the fix applied so you can test it and confirm that the bug is fixed with this commit.

https://mega.nz/file/nDwSWbIa#2ixhHR7pS4V1V6kNkBXrUpzCkLGM5UYsEDiplU4Cf_w

**Comment by JoePalffy** [comment]
Yes, it works now, thanks 👍
    On Friday, June 17, 2022, 05:28:27 PM GMT+3, Oleguer Llopart ***@***.***> wrote:  
 
 


Probably fixed in 5499e39

I leave you a version with the fix applied so you can test it and confirm that the bug is fixed with this commit.

https://mega.nz/file/nDwSWbIa#2ixhHR7pS4V1V6kNkBXrUpzCkLGM5UYsEDiplU4Cf_w
