### ISSUE TITLE
Feature request - m4a player

### ISSUE THREAD

**Issue by bumbaras** [ollm/OpenComic#149]
Hello. It is minor feature request - can m4a player be added which will recognize the file in episode folder and start to play? Webtoons is using this feature in some of their titles, some of them have many chapters with tracks, and the tracks can be acquired quite easily.
Of course this feature will be meaningless for other comics sources but still ...

**Comment by ollm** [comment]
Can you send me an example file or files so I can work on this feature?

My email: [oleguer.llopart.mora@gmail.com](mailto:oleguer.llopart.mora@gmail.com)

**Comment by ollm** [comment]
Closed as completed in 26947a297868e86069cc6daca77e1a3f016d0705 and available in [v1.2.0](https://github.com/ollm/OpenComic/releases)
