### ISSUE TITLE
Problem with zoom when using "Reading webtoon" 

### ISSUE THREAD

**Issue by Olivertgb** [ollm/OpenComic#155]
Hello! I downloaded OpenComic in order to read some webtoons however since I have one monitor and I use it horizontally I wanted to zoom out on the pages so that I could properly read them, however when you do this it only zooms out the current "page" you are looking at and when you scroll to the next "page" (so file) it goes back to the original zoom level which is far too high to read anything properly. This would be fine if entire chapters were single files and simply really long images however I have mine split into several files and so I think it would be really nice if it was possible to have a universal zoom level for the pages. Also I'm using the macOS version in case this is an issue specific to Mac. Thank you!

**Comment by ollm** [comment]
This is currently implemented in the master branch c94ac75d5f247a1f423b4192d1b1cab2c066be6f, you can download the beta below for macOS or build from source, also note that if you just want the image to fit the edges of the screen you can do so using the functions of `Reading webtoon`, `Adjust to width`, `Horizontal margin` and `Clip horizontal`, that will give you less problems.

https://mega.nz/file/zaY22CTY#mRvqFnHqJbfQ3fTTQTjxHY_631V93J4vrhOxALm3CvQ

![Captura desde 2023-04-12 16-31-20](https://user-images.githubusercontent.com/18549191/231491086-a1ce2a9e-fc00-4a0b-9766-cc753c8c44c6.png)
