### ISSUE TITLE
Add gamepad/controller support for couch reading

### ISSUE THREAD

**Issue by aorin1** [ollm/OpenComic#158]
OpenComic seems like the perfect solution for browsing libraries of magazines, comics and eBooks. Being able to browse through them using a gamepad far from the big screen is a very useful feature.

**Comment by aorin1** [comment]
Following the development installation guide and starting OpenComic, I paired a PS4 gamepad via bluetooth and it works great, specially using the webtoon view, it also respects analog acceleration properly and it feels great browsing through the pages with a controller, far from the big screen.

Having the ability to browse Configurations using the gamepad can be useful, specially if the user wants to add or remove folders, or opening single files.

Since X/Y are free, maybe Y could be used to bring the File menu and X add bookmarks? 
Most people have either the Xbox or PS controllers and the standard from other manufactures follow the same basic layouts and buttons, what about L3/R3 to reset zoom/toggle full screen?

Can OpenComic to be set to always open in full screen, by the way?

Dpad and left analog, along with L/R browse pages, I haven't used the Floating magnifying glass yet, but would it be possible to make it usable with the right analog?

OpenComic is probably the only CBZ/PDF reader with native gamepad support, with the upcoming improvements for reading PDF and populating thumbnails, I'll show this for thousands and they'll use it even for reading game manuals, magazines and more.

**Comment by ollm** [comment]
> Following the development installation guide and starting OpenComic, I paired a PS4 gamepad via bluetooth and it works great, specially using the webtoon view, it also respects analog acceleration properly and it feels great browsing through the pages with a controller, far from the big screen.
> 
> Having the ability to browse Configurations using the gamepad can be useful, specially if the user wants to add or remove folders, or opening single files.
> 
> Since X/Y are free, maybe Y could be used to bring the File menu and X add bookmarks? Most people have either the Xbox or PS controllers and the standard from other manufactures follow the same basic layouts and buttons, what about L3/R3 to reset zoom/toggle full screen?
 
Thanks for the button configuration suggestions, for now I have already implemented the ones for the R3/L3 buttons f42d37d982aaf2556a84b5197a239488df453c53 and d3c56985080455f221942259288f0a36b753cafc

What do you mean by "used to bring the File menu"? Show/hide left side menu?

> Can OpenComic to be set to always start in full screen, by the way?

I have added a preference in the settings to do this 68eff46dac6bf148cb500abe3d547aff11631609

> Dpad and left analog, along with L/R browse pages, I haven't used the Floating magnifying glass yet, but would it be possible to make it usable with the right analog?

Yes, I can try to see how it works.

> Apart from the controller, some CBZ/CBR/PDF files are returning errors when trying to open them, related to decompression or something, they work fine with another CBZ reader.
> [Window Title] Error when unzipping
> 
> [Main Instruction] An error occurred while trying to unzip the file.
> 
> [Content] invalid signature: 0x21726152

It seems that this file is a RAR file but with a ZIP (CBZ) extension, I have made it try to decompress the file as RAR when that signature is detected aa39a6a8b2e9d37d6ea5572d283d615c64d8250f

**Comment by aorin1** [comment]
> What do you mean by "used to bring the File menu"? Show/hide left side menu?

Mostly to add folders, open files and even exit the application using the gamepad, or it could be achieved by making the cursor (that is the same for choosing what magz/comics we want to open and browse pages) to be able to browse those tabs, but it could be a bit less ideal.

About the file issue, you're right, I extracted its content and created a zip out of the extracted pages without any compression "store" option, named it as cbz and OpenComic opened the file right away, showing its thumbnails, too.

Thanks for adding the option so OpenComic is able to start in full screen, the magnifying glass consideration and all the support and the buttons functions as well!

**Comment by ollm** [comment]
Closed as completed in 759ee6085399087408d6aec91cab25e732a53c15 and available in [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

Feel free to reopen the issue if you find any bugs.

**Comment by aorin1** [comment]
The latest 1.0.0-beta.1 build works fine with the controller and it's really nice to read it far from the big screen. It will be nice if the cursor isn't limited to just browsing the already added folders/files, making it possible to use a button dedicated to the menus and settings, like adding folders and preferences. Maybe adding a confirmation when pressing 'back' or a dedicated button to close the application, since there's no way to close OpenComic with the gamepad alone.

**Comment by ollm** [comment]
I reopen this until all the Gamepad functions are implemented, although I don't know if it will be possible to implement the possibility of adding folders without implementing a proper navigation system to select them.

**Comment by ollm** [comment]
I publish a new version with improved gamepad navigation https://github.com/ollm/OpenComic/commit/d1290f53fc99af0dc660052568c827d07dab74ca and gamepad shortcuts https://github.com/ollm/OpenComic/commit/0a4a4597883c7c6c837acdd61e4d80dc8c0a0ec1

### [v1.0.0-beta.2](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.2)

This includes the following improvements:

- Gamepad menu to close OpenComic and access to header bar menus.
- Control magnifying glass using right stick when is active.
- Navigate to the settings, language and theme pages.
- Personalize buttons actions in settings.

**Comment by ollm** [comment]
Due in the latest beta version ([v1.0.0-beta.5](https://github.com/ollm/OpenComic/releases)) all features have been implemented (Except for being able to add folders, but you can use the master folders as a replacement), I close for now the issue.

Any other function or bug related will have to open a new issue.
