### ISSUE TITLE
OpenComic becomes unresponsive in a blank screen after sitting in the background for a few minutes

### ISSUE THREAD

**Issue by aorin1** [ollm/OpenComic#159]
To reproduce this, open a PDF or possibly other formats and use other applications, such as browsing and so on, OpenComic will become unresponsive, with the screen shown below, clicking twice on Quit is required to force close the application.

![image](https://github.com/ollm/OpenComic/assets/32167620/a75d5a13-0c44-45b4-80e7-835e9126182e)

**Comment by ollm** [comment]
Do you still have this error in the new beta version? [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

**Comment by aorin1** [comment]
> Do you still have this error in the new beta version? [v1.0.0-beta.1](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.1)

I opened OpenComic and did many things while it was idle in the background and it was working fine when I focused on it again, no blank screens so far, I'm closing the issue, thanks again!
