### ISSUE TITLE
[Feature Request] Scroll with mouse cursor on zooming

### ISSUE THREAD

**Issue by HDark15** [ollm/OpenComic#163]
I want this feature the most because I've been using https://kanryu.github.io/quickviewer/ for a long time, but it's been abandoned and has a lot of great features that I want in this project.

**Comment by ollm** [comment]
It refers to the following, it is currently available in the beta version ([v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3))

https://github.com/ollm/OpenComic/assets/18549191/0a09d558-4280-4286-86de-d62abd2f8f59

**Comment by ollm** [comment]
Thanks for the example video, I have implemented it (e8cc79cbddd23ff7d47b7046190cecbad199d3c2) and added the option in the settings (Enabled by default), I have also added an option to scroll with the same method (Disabled by default).

This will be available when [v1.0.0-beta.4](https://github.com/ollm/OpenComic/blob/master/CHANGELOG.md) is released, although if you prefer you can build it from source: https://github.com/ollm/OpenComic#build-from-source

I will update and close this issue when I release the version.

#### Move zoom with mouse:

https://github.com/ollm/OpenComic/assets/18549191/d1bf5db9-76ee-43df-9c84-560374b41392

#### Scroll with mouse:

https://github.com/ollm/OpenComic/assets/18549191/c07d2217-1f3a-4ea0-ad66-292239f62897

**Comment by ollm** [comment]
I have improved the detection of the edge of the image (Margins included) to fix this, now the zoom cannot be moved outside of it, it also applies to drag and drop e7ec77104360b1e2ac2aa96d97b6c1d2cc2d6d01


https://github.com/ollm/OpenComic/assets/18549191/3e24633a-7564-4b22-9985-e0a114bf831b

**Comment by ollm** [comment]
The version [v1.0.0-beta.4](https://github.com/ollm/OpenComic/releases) is now available with this feature.

Currently there is only a small bug that happens when activating the original size of the image using the mouse middle click, that in some cases some of the edges cannot be reached, but it is rare that it happens (I will try to fix it later)

Feel free to comment if you find any others bugs.

**Comment by ollm** [comment]
I have opened a new issue for this, since it is a different feature, you can subscribe to it to get updates https://github.com/ollm/OpenComic/issues/169
