### ISSUE TITLE
[Feature Request]: Automatic dark mode

### ISSUE THREAD

**Issue by NomarCub** [ollm/OpenComic#164]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

The app should have an option to follow the system theme, and switch to dark or light mode when the OS does.

**Comment by ollm** [comment]
Closed as completed in 3d804032f0766b111888878a220039711161d94b and available in [v1.0.0-beta.5](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.
