### ISSUE TITLE
Submit v1.0.0-beta.4 Simplified Chinese language

### ISSUE THREAD

**Issue by kofzhanganguo** [ollm/OpenComic#167]
[zh-hans.json](https://github.com/ollm/OpenComic/files/13208773/zh-hans.json)

Simplified Chinese language has been fully translated. Since I don’t know how to submit it to the official, I can only submit it to the author here.

**Comment by ollm** [comment]
Thanks for the updated translation, I added it to the master branch de3a9e4fe29f43c553f6f9870596e1a0e5cee265

You can submit the translations by making a pull request ([Examples](https://github.com/ollm/OpenComic/pulls?q=is%3Apr+Translate)) or opening an issue as you have already done (Whatever you prefer)

**Comment by kofzhanganguo** [comment]
> 感谢更新翻译，我将其添加到主分支[de3a9e4](https://github.com/ollm/OpenComic/commit/de3a9e4fe29f43c553f6f9870596e1a0e5cee265)
> 
> 您可以通过提出拉取请求（[示例](https://github.com/ollm/OpenComic/pulls?q=is%3Apr+Translate)）或像您已经完成的那样打开问题来提交翻译（无论您喜欢什么）

The main thing is that I don't use pull requests. If the translation changes, I'll submit the latest translation to you.
