### ISSUE TITLE
[Bug]: Inability to Delete Items From Library

### ISSUE THREAD

**Issue by gokieks** [ollm/OpenComic#171]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.0.0-beta4

### Operating System

macOS Big Sur 11.7.10

### Steps to reproduce

1. Add folder to Library.
2. Attempt to delete from Library.

### Expected Behavior

In 0.2.1, when right clicking an item in the "Comics" section, there was only one option (Remove) which will delete the item as expected.

### Actual Behavior

In 1.0.0-beta4, when right clicking an item in the "Library" section, there are two options (Add poster and Open folder location), and there does not appear to be any other way to delete an item.

**Comment by ollm** [comment]
Closed as fixed in 24ba9ba787130c8f92b098cfefefdb7d37d18549 and available in [v1.0.0-beta.5](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.
