### ISSUE TITLE
[Bug]: No Way to Close the "About OpenComic" Pop Up

### ISSUE THREAD

**Issue by gokieks** [ollm/OpenComic#172]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.0.0-beta4

### Operating System

macOS Big Sur 11.7.10

### Steps to reproduce

1. Help > About OpenComic.
2. Attempt to close the newly created pop up UI element and return to main app.

### Expected Behavior

Either a text ("OK", "Close", etc.) or icon ("X") button to close the pop up and allow for using the app as normal again.

### Actual Behavior

The frame can be resized, but there are no visual elements that indicate it can be closed:
![image](https://github.com/ollm/OpenComic/assets/7364586/a956150a-169c-424b-afc9-561036e91b79)

The normal keys that one might try (Esc, Enter, Space) to close it do nothing, and as far as I can tell the only option is to quit the application completely and re-open it.

**Comment by Pasqua101** [comment]
Hey @ollm, if it's possible can I tackle this issue? I know you self-assigned it, but if it's possible, can I take over? Seems like it should be a quick and easy fix. Just need to be pointed to the file that is creating the alert window.

**Comment by ollm** [comment]
Hi @Pasqua101, this is currently fixed in master branch 40ae6d1caa80bb404d4986af1d0853e2bbec5eed, sorry for not telling you, I was waiting to publish the next beta to close all related issues.

Also the error reported in the other issue has also fixed in master #171 24ba9ba787130c8f92b098cfefefdb7d37d18549

I'll let you know when the beta is available.

**Comment by Pasqua101** [comment]
No worries, thank you for letting me know.

**Comment by ollm** [comment]
Closed as fixed and available in [v1.0.0-beta.5](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.
