### ISSUE TITLE
[Bug]: Exit fullscreen from Recents not possible

### ISSUE THREAD

**Issue by Senshi00** [ollm/OpenComic#176]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

v1.0.0-beta.5 (flatpak)

### Operating System

Arch Linux 6.6.2-arch1-1

### Steps to reproduce

1. Open .cbz from Recents
2. Enter fullscreen F11
3. Navigate back to Recents and try to exit fullscreen with F11
4. Error thrown
![image](https://github.com/ollm/OpenComic/assets/27438059/f167a045-9ca3-4a49-b361-8c930fdc3894)

Fullscreen can be exited fine when opening the comic again and pressing F11 there or from the Library menu

### Expected Behavior

Exit fullscreen from Recents

### Actual Behavior

Error is thrown and fullscreen is active (No titlebar shown, but menu options like file, view etc. are visible.)

**Comment by ollm** [comment]
Closed as fixed in 829173058bb3dde12d35b726070c19ec43a63be3 and available in [v1.0.0](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.
