### ISSUE TITLE
[Bug]: Freezes when i go back to folder

### ISSUE THREAD

**Issue by anotherduckling** [ollm/OpenComic#178]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

v1.0.0-beta.5

### Operating System

Windows 11

### Steps to reproduce

1. Opened a manga
2. Went back to the containing folder while manga was loading
3. It freezes and shows this dialogue
![image](https://github.com/ollm/OpenComic/assets/57977673/f6ec4064-6081-4d3a-a0a2-a2175df13420)

### Expected Behavior

It should go back

### Actual Behavior

it freezes

### Error message

![image](https://github.com/ollm/OpenComic/assets/57977673/c4ded19a-01c7-49b5-82b9-39e7a9c31d5c)

**Comment by ollm** [comment]
I haven't been able to replicate the exact bug, but I have fixed some errors that appeared when going back before the manga was fully loaded (99fb29dab7b07a94883199665167a1301774f4e8), one of these may be related to yours.

When the next beta version is available with the fix I will let you know again.

**Comment by ollm** [comment]
Closed as possibly fixed in 99fb29dab7b07a94883199665167a1301774f4e8 and available in [v1.0.0](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.
