### ISSUE TITLE
[Bug]: Changing library view in a folder opens up the recent manga of that folder

### ISSUE THREAD

**Issue by anotherduckling** [ollm/OpenComic#179]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

v1.0.0-beta.5

### Operating System

Windows 11

### Steps to reproduce

1. Open a folder that contains manga with recent read history
2. Change the layout from grid to list

### Expected Behavior

It will only change the view from grid to list

### Actual Behavior

It changes the view style but also opens up the manga

### Sample file

https://github.com/ollm/OpenComic/assets/57977673/9d12917d-c278-4b11-818c-adf3c6e0552f

**Comment by ollm** [comment]
Closed as fixed in e8e2c16a18d8f0c03b6b00b09a7c0d1bf8a24032 and available in [v1.0.0](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.
