### ISSUE TITLE
Keep Cached files after closing app

### ISSUE THREAD

**Issue by Megatro-nn** [ollm/OpenComic#180]
Some comics are of a big size and it's really annoying to unzip them every time to open the app so it would be great if there is an option to keep them after closing app or automatically deleting them after finishing the book.

**Comment by ollm** [comment]
I can add the maximum size option for temporary files, and keep the most used files when closing the app, similar to how the maximum cache size currently works.

**Comment by Megatro-nn** [comment]
Yes, that would work but 1024MB as a maximum size for temporary is small so it will be great if its larger.

**Comment by ollm** [comment]
Closed as completed in a7272499407191064f9d6bd7c42ecf3bb1231a83 and available in [v1.1.0](https://github.com/ollm/OpenComic/releases)
