### ISSUE TITLE
[Bug]: zoom bug in vertical reading if global zoom disabled

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#183]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.0.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

1. Disable global zoom
2. Open webtoon
3. Set vertical reading
4. Scroll and stop between pages
5. Click "original size"

### Expected Behavior

Current page set in original size, next page moved out of view

### Actual Behavior

Next page is still visible and overlap current page

### Additional Information

<details>
<summary>Screen record</summary>

https://github.com/ollm/OpenComic/assets/96221151/49c54d1e-629c-4bec-97ea-5ddc2289f998
</details>

**Comment by dajotim937** [comment]
Tell me if I should make separate issue.

One more but with "original size" zoom. I have white lines at places where images are stitched
<details>
<summary>Screen record</summary>

https://github.com/ollm/OpenComic/assets/96221151/2092f6c3-d92d-4102-b716-668d6927dbf7
</details>

**Comment by ollm** [comment]
You can leave the issue report here, since it could be related, I will open another issue if the error is not related.

**Comment by ollm** [comment]
Closed as completed in https://github.com/ollm/OpenComic/commit/f83d17fbf3cb581d8b8735050cb919fca623d8aa and available in [v1.1.0](https://github.com/ollm/OpenComic/releases)

**Comment by dajotim937** [comment]
![image](https://github.com/ollm/OpenComic/assets/96221151/1ff3c061-b35d-4d13-9daf-afe2d4638548)

Still has white lines at places where images are stitched for some files. Old ones from video above has disappeared.

**Comment by dajotim937** [comment]
![2024-01-17_23-22-59](https://github.com/ollm/OpenComic/assets/96221151/e848c865-3ff1-40fb-bbfd-0fe5ba569c5d)
![2024-01-17_23-22-50](https://github.com/ollm/OpenComic/assets/96221151/db2bb554-4a76-4606-9945-eef29cbcdb7b)

Here is same file and basically same picture. On screens there is page 14,15,16. Stitch between 14 and 15 without white line, but between 15 and 16 with white line.

**Comment by dajotim937** [comment]
> make sure you are using the option "Do not enlarge more than its original size"

Already did.


> It would also help to know what scale you are using on your monitor.

Never used scale. So it's 100% in settings.

**Comment by dajotim937** [comment]
I downloaded same chapter from screenshots above and looks like yeah, the issue with images itself. Checked in SumatraPDF and also got line. And checked in Photoshop. Sorry. I'll write here again if I find line there it shouldn't be, but looks like it's fixed.

<details>
<summary>PS screenshots</summary>

![2024-01-20_06-24-01](https://github.com/ollm/OpenComic/assets/96221151/2cdb2366-2399-409a-9a0e-985a698594d3)
![2024-01-20_06-23-49](https://github.com/ollm/OpenComic/assets/96221151/f6985ee6-b387-4904-a604-644edfd3bdd3)
</details>
