### ISSUE TITLE
[Bug]: "continue reading" doesn't check if file exists

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#184]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.0.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

1. Add folder with cbzs.
2. Open file
3. Close OpenComic
4. Rename files

### Expected Behavior

I guess, continue reading should show warning or something

### Actual Behavior

It shows that you still can continue reading from file that has been rename. If you click on banner, it opens empty view panel.

**Comment by ollm** [comment]
I will add a file exists check, if not, would you prefer that the continue reading not be shown or show the most recently read file that the file exists?

**Comment by ollm** [comment]
Closed as completed in 7aee55ca5dac6b937824728b7ded116dc00c28df and available in [v1.2.0](https://github.com/ollm/OpenComic/releases)
