### ISSUE TITLE
[Feature Request]: samba support

### ISSUE THREAD

**Issue by krakerz** [ollm/OpenComic#185]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

as per title said, it would be great if it can read from samba location, like \\server\manga\[directory]
as per now, it's get errors ENONT something with \server\manga\[directory] error

**Comment by ollm** [comment]
I'll try to see if there is any `samba` client implementation that works correctly in `Node.js`, if it doesn't exist, I don't think it's possible to implement this in OpenComic.

**Comment by ollm** [comment]
I have add support for `samba` and others protocols (`smb://`, `ftp://`, `ftps://`, `scp://`, `sftp://` and `ssh://`) 52a09a9aad601a2e70b8f0011a6fddc7d3e9023a, this is available in [v1.1.0](https://github.com/ollm/OpenComic/releases)

You can add you `samba` server from settings:

![Servers](https://github.com/ollm/OpenComic/assets/18549191/30abcef2-249d-4662-8d2b-2932cdf883b5)

If you find any bug, you can open a new issue.
