### ISSUE TITLE
[Feature Request]: Favorites

### ISSUE THREAD

**Issue by bobmower00** [ollm/OpenComic#187]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

It would be great if there was a feature for favorites. Specifically, there could be an option to favorite a comic being viewed while reading it. Then on the home menu somewhere you could look at all of your favorites in a collection.

**Comment by ollm** [comment]
Closed as completed in 86039e6d9f90d77b9671068d520c8bc2fa635f30 and available in [v1.1.0](https://github.com/ollm/OpenComic/releases)
