### ISSUE TITLE
Attempting to call a function in a renderer window that has been closed or released. Function provided here: undefined

### ISSUE THREAD

**Issue by nephaste** [ollm/OpenComic#19]
Hi thanks for this good project

i try to integrate it as a qpkg for Qnap NAS HDStation
which is an ubuntu1804 LXC container

on first try.. opencomic binary refuse to start
i had to force it with the flag --no-sandbox   all run as root, no others user possible

./opencomic --no-sandbox

in this mode it start and opens, but what ever i do in menu... stdout showup this error, and nothin happen

Attempting to call a function in a renderer window that has been closed or released.
Function provided here: undefined

any idea ?

**Comment by ollm** [comment]
I have executed the binary (tar.gz) and it seems that the symbolic links of the sharp package have been broken.

At the moment you can correct this problem following these steps:

- Download the following [file](https://drive.google.com/file/d/1_f4The7ebsX4t7DVPef-BR9nuvOPy9Hm/view?usp=sharing) and extract it, it contains the vendor folder of the sharp package with the symbolic links correctly.
- Go to `opencomic-0.1.4/resources/app.asar.unpacked/node_modules/sharp/` replace the vendor folder with the one you just downloaded.

Now run again the binary, it should be executed without problems.

I will try to find out why symbolic links are broken when packaging.

**Comment by nephaste** [comment]
thanks a lot for the quick fix... it runs and it is published on QnapClub repo Appcenter

https://www.qnapclub.eu/fr/qpkg/794

**Comment by ollm** [comment]
If you prefer, you can also obtain the vendor folder by cloning the repository and installing the dependencies.

```
git clone https://github.com/ollm/OpenComic.git
cd OpenComic
npm install
```

Then the folder would be found in `OpenComic/node_modules/sharp/vendor`

**Comment by nephaste** [comment]
thanks
