### ISSUE TITLE
[Bug]: Running OpenComic w/ Electron and unpacked ASAR erroneously opens ASAR as a comic

### ISSUE THREAD

**Issue by pluiedev** [ollm/OpenComic#191]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0

### Operating System

NixOS 24.05 (Uakari)

### Steps to reproduce

1. Build OpenComic as an unpacked folder via `npm run prebuild && electron-builder build --dir`
2. Run OpenComic via `electron ./dist/linux-unpacked/resources/app.asar`

### Expected Behavior

OpenComic opens and greets the user as if no file is selected for browsing.

### Actual Behavior

OpenComic attempts to open the built app.asar as a comic in the file browser, which does not crash the app but instead falsly opens the ASAR file as an archive, and revealing the folders inside, preventing the app from opening actual paths to image files in argv.

### Additional Information

I'm doing this as a part of a packaging request for Nixpkgs (NixOS/nixpkgs#280883), and it's accepted in Nix to build wrapper scripts around `electron path/to/app.asar` as the executable file as other options such as rpm or deb don't apply. I took a look at [the code that opens comic files based on argv](https://github.com/ollm/OpenComic/blob/a901754a4274687cddbfa3820ca3667b8b80e6ee/scripts/opencomic.js#L115-L119) and it looks like we might have to code in an exception, or find some other way of avoiding this happening.

**Comment by ollm** [comment]
Thank you for the report.

This should solve it b7beeff17b2e9157a613481df6ec603f86b10ddc
