### ISSUE TITLE
[Feature Request]: name of file in title of app window

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#192]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

1st feature: show title of currently opened file in app title (windows alt+tab shows only "OpenComic" right now. **UPD: Completed in test build.**

2nd feature: option to disable open next/prev file with mouse scroll. I would like to use scroll to navigate inside opened file(webtoon) and use either arrow from keyboard or button in app on top to open next or prev file. **UPD: Completed in test build.**

3rd: button on panel to open location of currently opened file. **UPD: Completed in test build.**

**Comment by dajotim937** [comment]
About 2nd feature: I guess you can also disable delay before open next chapter (I mean when at bottom/top shows small panel with loading circle before actually open and load file). It's basically lost it purpose when user disable go next/previous chapter with mouse scroll. You can't stop this delay with scroll like when you use scroll to to next/prev chapter and you have intentionally open next/prev chapter with keyboard or button on panel (so there is no accidentally opens when you need this delay).

**Comment by ollm** [comment]
You can disable this delay in the reading mode, editing global configuration, custom configuration or current configuration.

![Captura desde 2024-01-27 18-15-01](https://github.com/ollm/OpenComic/assets/18549191/7835f0b4-bf1c-4084-aa4b-7fd1dc1e1025)

**Comment by dajotim937** [comment]
Oh, missed it. Thanks.

**Comment by dajotim937** [comment]
![2024-02-16_13-43-29](https://github.com/ollm/OpenComic/assets/96221151/bfef3310-18bb-4f1e-a6a7-f443db2c0577)

I don't know is this bug or intended behavior. Filename `Lout of Count's Family c000 (2020) (Digital) (Dalte).cbz` but in title `S1 c000` which is name of folder inside cbz file.

**Comment by ollm** [comment]
Closed as completed/fixed in d31bcdc76ca649f2d3b05c05bdc9096bffbdd5f7 and available in [v1.2.0](https://github.com/ollm/OpenComic/releases)
