### ISSUE TITLE
[Bug]: Some bug

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#194]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

Didn't anything special, just read manhwa in full screen mode. Got that message multiple times on different files.
I think most (or all, I don't remember first ones) messages shows when you open next file.

### Expected Behavior

-

### Actual Behavior

![2024-01-18_00-35-44](https://github.com/ollm/OpenComic/assets/96221151/f403e15e-4d29-445d-95a1-ec9a50dea21e)

<details>
<summary>Error from devtools</summary>

```
opencomic.js:872 Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at escapeBackSlash (opencomic.js:872:16)
    at opencomic.js:1075:9
    at Function.<anonymous> (opencomic.js:985:13)
    at Function.each (C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:383:19)
    at opencomic.js:984:6
    at Function.each (C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:383:19)
    at Object.<anonymous> (opencomic.js:974:4)
    at Object.wrapper (wrapHelper.js:10:19)
    at 7 (C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\builded\templates.js:2443:100)
    at Object.prog [as fn] (runtime.js:333:12)
    at Object.<anonymous> (if.js:19:22)
    at Object.wrapper (wrapHelper.js:10:19)
    at 2 (C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\builded\templates.js:2428:47)
    at prog (runtime.js:333:12)
    at execIteration (each.js:50:9)
    at Object.<anonymous> (each.js:63:13)
escapeBackSlash		 @ opencomic.js:872
(anonymous)		 @ opencomic.js:1075
(anonymous)		 @ opencomic.js:985
each			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:383
(anonymous)		 @ opencomic.js:984
each			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:383
(anonymous)		 @ opencomic.js:974
wrapper			 @ wrapHelper.js:10
7			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\builded\templates.js:2443
prog			 @ runtime.js:333
(anonymous)		 @ if.js:19
wrapper			 @ wrapHelper.js:10
2			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\builded\templates.js:2428
prog			 @ runtime.js:333
execIteration		 @ each.js:50
(anonymous)		 @ each.js:63
wrapper			 @ wrapHelper.js:10
1			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\builded\templates.js:2405
prog			 @ runtime.js:333
execIteration		 @ each.js:50
(anonymous)	 	 @ each.js:63
wrapper			 @ wrapHelper.js:10
main			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\builded\templates.js:2526
main			 @ runtime.js:230
ret		 	 @ runtime.js:250
loadTemplate		 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\template.js:8
addHtmlImages		 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:253
images.<computed>.onload @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:4935
load (async)
(anonymous)		 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:4923
each			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:383
each			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\node_modules\jquery\dist\jquery.js:205
read			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:4917
openComic		 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\dom.js:2102
await in openComic (async)
(anonymous)		 @ VM1165:1
setTimeout (async)
showNextComic		 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:1585
stayInLine		 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:736
resized			 @ C:\Users\***\AppData\Local\Programs\OpenComic\resources\app.asar\scripts\reading.js:2503
```

</details>

Also, with this error message, view area becomes white and image align left with some margin.
Also, I think the issue rise when OpenComic and other app trying to get access to HDD at same time (new file that is opening and other app also write something on same HDD).
UPD: or maybe alt+tab triggers something while loading next file.

**Comment by dajotim937** [comment]
Same situation, but different error.
![2024-01-18_02-17-18](https://github.com/ollm/OpenComic/assets/96221151/758394f5-0f16-41c4-bf39-7fe6cbea1d7a)

**Comment by dajotim937** [comment]
> UPD: or maybe alt+tab triggers something while loading next file.

Related: Alt+tab in fullscreen mode cause jump to some fixed position.

<details>
<summary>Screen record</summary>

https://github.com/ollm/OpenComic/assets/96221151/bee285e2-25b6-4b1a-94da-4acc001d96b8

</details>

**Comment by ollm** [comment]
Thanks for the reports.

I have fixed most of the bugs (And those of the other issues), you can try the following build and test if there are still any that happen.

- Improve stay in line in vertical reading 2a6254ae3875e08fd329b5410bd9156962cac6bc
- Some errors in scroll reading a4887c3
- Some errors on reading in scroll 1485b25c39eb1ebfcd352d7920e7a08c4d2af6f5
- Next chapter button not work inscroll mode if last page is smaller than the window and "Adjust to width" is enabled 2bbd49e
- Error when pressing a key at startup 8f57f65c3b13d37eb49ac4e8cfd251c5d9a06509

Build with fixes: https://mega.nz/file/Hf4WRTIL#_gfCjq91K3T8aTWCbjmxm2t0rcJwxnpyI3v4Elxl9Lk

This build also has some of the features requested in other issues.

- Show the current reading title in app window 9520faa
- Option to open file location of current reading from the file menu c9215dc
- Setting to enable/disable go next/previous chapter with mouse scroll (Vertical reading) 37612bfdce13ce73348bda997bf3aeb32b8915af

**Comment by dajotim937** [comment]
Okay, thank you. I'll comment in relevant issues if I get those bugs again.

**Comment by dajotim937** [comment]
> Related: Alt+tab in fullscreen mode cause jump to some fixed position.

It's still there, but lesser than before. Mostly I can see only small movements but in general chapter stays on same position. But sometimes it still jumps.

<details>
<summary>Screen record</summary>

https://github.com/ollm/OpenComic/assets/96221151/d62c244e-82f9-41dc-b17b-5d0abb674491

</details>

**Comment by dajotim937** [comment]
![2024-01-27_18-23-00](https://github.com/ollm/OpenComic/assets/96221151/275ac843-30cd-4427-9ed9-0412ec8e8d45)

<details>
<summary>Error from devtools</summary>

![2024-01-27_18-26-02](https://github.com/ollm/OpenComic/assets/96221151/60224ec0-9714-4900-a1b9-fc523caa1528)

</details>


Same situation. I click button on keyboard to open next chapter, alt+tab, got 3 same error window. In devtools there is 2 error message.

**Comment by dajotim937** [comment]
![2024-01-27_18-31-41](https://github.com/ollm/OpenComic/assets/96221151/508e9a68-6f7a-484b-a131-0c303202437b)

This one was not with alt+tab, but with F11 key (exit from fullscreen) when file was loading, I guess.

**Comment by ollm** [comment]
It seems that the two errors occur when resizing the window before it loads (One when activating full screen and the other with alt+tab).

Try this build with this fix 770afba6bd58e54b5ed33533bbc668cff49bca9b https://mega.nz/file/vCAj3RRD#qt89OlMa7jXHXtquckMMmTGeRmsjhYaTIP8iYHLWGXA

The full screen jump bug seems to be because a resize event is also triggered when using alt+tab in fullscreen, OpenComic tries to keep the image centered, but sometimes it doesn't seem to work correctly.

**Comment by dajotim937** [comment]
Tested a bit. Looks like previous errors are gone. Now I don't get any error messages, but there is still error message in console.

![2024-01-30_01-04-27](https://github.com/ollm/OpenComic/assets/96221151/354dbc73-a6ed-428c-93f1-20c4efb05b69)

**Comment by dajotim937** [comment]
Said me, and immediately got an error when exiting from fullscreen while chapter was loading.

![2024-01-30_05-27-30](https://github.com/ollm/OpenComic/assets/96221151/b04b406d-b073-460e-a6e5-8e73f12a3963)

**Comment by dajotim937** [comment]
Not sure how I got this error. I think it happens when I load next chapter and click back button on the pannel (left one button).

![2024-01-30_08-09-12](https://github.com/ollm/OpenComic/assets/96221151/9875e7fd-4ce0-4228-867f-89df3a3ae709)
![2024-01-30_08-09-36](https://github.com/ollm/OpenComic/assets/96221151/5447c92d-9e38-4232-9cf0-b5787093ca8c)

**Comment by dajotim937** [comment]
![2024-01-31_17-21-22](https://github.com/ollm/OpenComic/assets/96221151/f4d855c3-5bfb-4949-b948-6047183a2e77)

This one also didn't show any error messages, only in console.

**Comment by dajotim937** [comment]
> The full screen jump bug seems to be because a resize event is also triggered when using alt+tab in fullscreen

I guess this one also related to your message. Can't scroll past some position in fullscreen (F11).
Not webtoon mode (but still vertical), and used custom zoom in.

https://github.com/ollm/OpenComic/assets/96221151/4a9e0a9b-05cf-4f04-9983-3a497c8381f9

**Comment by dajotim937** [comment]
One more error. Happens when folder has corrupted cbz file. In my case it was created file from torrent but it hasn't been download when I opened OpenComic (because I downloaded to folder that I added as master folder).

![2024-03-07_14-51-04](https://github.com/ollm/OpenComic/assets/96221151/5ab0f059-f18f-438b-9dfd-084926c083e6)

**Comment by dajotim937** [comment]
![2024-03-18_03-22-02](https://github.com/ollm/OpenComic/assets/96221151/e24ed6c8-bb04-4c4a-87dc-bc281b63f864)


<details>
<summary>Error from devtools</summary>

```
node:internal/validators:163 Uncaught TypeError: The "path" argument must be of type string. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:490:5)
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.normalize (node:path:305:5)
    at Readable.<anonymous> (C:\Users\***\AppD…-manager.js:1828:34)
    at Readable.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Object.bodyData (C:\Users\***\AppD…\src\maybe.js:77:12)
    at C:\Users\***\AppD…src\events.js:83:11
    at Socket.<anonymous> (C:\Users\***\AppD…\lifecycle.js:64:51)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
__node_internal_captureLargerStackTrace	@	node:internal/errors:490
NodeError	 @ node:internal/errors:399
validateString	 @ node:internal/validators:163
normalize	 @ node:path:305
(anonymous)	 @ C:\Users\***\AppD…ile-manager.js:1828
emit	         @ node:events:513
addChunk	 @ node:internal/streams/readable:324
readableAddChunk @ node:internal/streams/readable:297
Readable.push	 @ node:internal/streams/readable:234
bodyData	 @ C:\Users\***\AppD…-7z\src\maybe.js:77
(anonymous)	 @ C:\Users\***\AppD…7z\src\events.js:83
(anonymous)	 @ C:\Users\***\AppD…src\lifecycle.js:64
emit             @ node:events:513
addChunk	 @ node:internal/streams/readable:324
readableAddChunk @ node:internal/streams/readable:297
Readable.push	 @ node:internal/streams/readable:234
onStreamRead	 @ node:internal/stream_base_commons:190
```

</details>

**Comment by dajotim937** [comment]
![2024-03-18_03-44-49](https://github.com/ollm/OpenComic/assets/96221151/fd7d20ba-4bd0-4bab-b80d-1ef6e814f4c0)


<details>
<summary>Error from devtools</summary>

```
C:\Users\***\AppD…scripts\dom.js:1194 Error: incomplete frame
    at Object.readJson (C:\Users\***\AppD…pts\cache.js:229:33)
    at file.readCompressed (C:\Users\***\AppD…e-manager.js:207:20)
    at file.read (C:\Users\***\AppD…le-manager.js:65:24)
    at file.images (C:\Users\***\AppD…e-manager.js:445:36)
    at getFolderThumbnails (C:\Users\***\AppD…ipts\dom.js:1166:28)
    at C:\Users\***\AppD…ripts\dom.js:245:25
    at async Object.loadIndexPage (C:\Users\***\AppD…ripts\dom.js:778:19)
getFolderThumbnails       @ C:\Users\***\AppD…scripts\dom.js:1194
await in getFolderThumbnails (async)        
(anonymous)               @ C:\Users\***\AppD…\scripts\dom.js:245
Promise.then (async)        
loadFilesIndexPage        @ C:\Users\***\AppD…\scripts\dom.js:167
loadIndexPage             @ C:\Users\***\AppD…\scripts\dom.js:778
onclick                   @ index.html:1
```

</details>
