### ISSUE TITLE
[Bug]: Last page / Next chapter button on panel has wrong state if last page is small

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#195]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0 (well, I'm using your custom test build for me)

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

1. Webtoon with last page smaller than current vertical size of reading area.
2. Webtoon reading view.
3. Click either last page button or click on last page from left side scroll panel

### Expected Behavior

Button should change to "next chapter" since there nothing left to scroll (full last page fit into vertical size of reading area)

### Actual Behavior

App showing "last page" button like there is something left to scroll. Clicking on it scroll webtoon up a bit, clicking again scroll to the end and changing button to "next chapter".

**Comment by dajotim937** [comment]
**Fixed in test build.**

**Comment by dajotim937** [comment]
Related: boundary situation, if you scroll last chapter with arrow key and last page is small last page/next chapter will have wrong state. Not that it doesn't matter but still.

And suggestion: open manga page after reading last chapter and clicking next chapter button.

**Comment by dajotim937** [comment]
Related:

https://github.com/ollm/OpenComic/assets/96221151/502e9d53-88f3-4a03-94c2-677ca648be90

**Comment by ollm** [comment]
Can you confirm if the error still occurs in latest version [v1.2.0](https://github.com/ollm/OpenComic/releases)?

**Comment by dajotim937** [comment]
Original bug from first comment is fixed, related bug from https://github.com/ollm/OpenComic/issues/195#issuecomment-1916326113 is not fixed.

Additional info: bug from video is happened only when there is next chapter. If there isn't, it scroll to the end as intended.

**Comment by ollm** [comment]
Fixed in cae6b6c65222d528705e44f6eee08feab3ec9adb

Build: https://mega.nz/file/nbQUlDIJ#iVhuBj0ES_H4VUCR0Kl36l980bmSBkYmKKmNpt0anpA

**Comment by dajotim937** [comment]
Looks like I can't reproduce it anymore.

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
