### ISSUE TITLE
[Bug]: fullscreen bug, kinda

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#199]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0 (well, I'm using your custom test build for me)

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

1. Set `Start reading in full screen` as false
2. Open chapter
3. F11
4. Alt+F4
5. Reopen OpenComic
6. Open chapter again

### Expected Behavior

Chapter is open in default non fullscreen mode

### Actual Behavior

Chapter is open in fullscreen mode like when `start reading in full screen` setting is set to true (not same as F11 fullscreen, because top bar with "File", "View", etc is still visible).

**Comment by ollm** [comment]
Closed as completed in 644cd26eed86d3f06bf473dbbfc9f13651da47b2 and available in [v1.2.0](https://github.com/ollm/OpenComic/releases)
