### ISSUE TITLE
falha no npm star

### ISSUE THREAD

**Issue by leirton52** [ollm/OpenComic#20]
Olá,

eu estava tentando rodar o Open Comic a partir do repositório do git, realizei os seguintes passos:

 - git clone https://github.com/ollm/OpenComic.git
 - npm install --only = dev
 - npm start
Na parte do npm start deram alguns erros de módulos que estavam faltando e eu os instalei manualmente. tentei dar um npm start novamente, mas ocorreu o seguinte erro que não consigo resolver:

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: win.removeMenu is not a function
    at createWindow (/home/leirton/OpenComic/scripts/main.js:49:6)
    at App.app.on (/home/leirton/OpenComic/scripts/main.js:104:2)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
Como faço para solucionar esse erro?

**Comment by ollm** [comment]
It has skipped some steps in the installation, such as `npm install` and `npm run rebuild`

I recommend you clone the repository again.

Here is a list with all the commands to be executed and in the corresponding order:

```
git clone https://github.com/ollm/OpenComic.git
cd OpenComic
npm install
npm install --only=dev
npm run rebuild
npm start
```
