### ISSUE TITLE
[Bug]: Can't copy or paste inside Mac app

### ISSUE THREAD

**Issue by itripley** [ollm/OpenComic#200]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0

### Operating System

macOS Sonoma

### Steps to reproduce

1. Copy 2.Paste

### Expected Behavior

Paste

### Actual Behavior

Not pasting

**Comment by dajotim937** [comment]
But. What are you trying to copy-paste?

**Comment by itripley** [comment]
Anilist key

**Comment by Eyolej** [comment]
Same problem here.

**Comment by ollm** [comment]
Closed as completed in 91cf4c8fb4d4ca357e21041d6d761029638fb817 and available in [v1.2.0](https://github.com/ollm/OpenComic/releases)
