### ISSUE TITLE
[Feature Request]: Add S3 server support

### ISSUE THREAD

**Issue by yutthaphon** [ollm/OpenComic#202]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

I hosted many comics on the S3 server and I want to read them with OpenComic.

**Comment by ollm** [comment]
Closed as completed in ae8c13323a1edf618923c40b600fc5dd43c61276 and available in [v1.2.0](https://github.com/ollm/OpenComic/releases)

![Captura desde 2024-03-29 17-43-02](https://github.com/ollm/OpenComic/assets/18549191/ed4cb364-5797-4bd0-95c3-ae91b6f67485)

If you find any bug, you can open a new issue.
