### ISSUE TITLE
[Bug]: cbz with corrupted image inside freezes app

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#204]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0 (well, I'm using your custom test build for me)

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

1. Add cbz with corrupted image
2. Open OpenComic

### Expected Behavior

Probably like Honeyview that shows all images except broken one.

### Actual Behavior

App freezes

**Comment by ollm** [comment]
Can you send me the CBZ file that is causing the bug? oleguer.llopart.mora@gmail.com

**Comment by dajotim937** [comment]
Done.

**Comment by ollm** [comment]
I have fixed the freezing problem when opening corrupt cbz files 05eefb3a9dcc549ab8d13da6b9cd5e27ed1239fd, but I have not been able to partially read the contents of the file that you have sent me, at least with [unzipper](https://www.npmjs.com/package/unzipper), I could try to try a different node package, since I have tried with different applications and some of them partially open the file.

Build with fix: https://mega.nz/file/zXglnC7R#YnHNrUcUOLOAbTSUBPHwo9GwRjt-vB88cL3yJ6GsXiY

If you can check if the following error has also been fixed https://github.com/ollm/OpenComic/issues/194#issuecomment-1984732763

**Comment by dajotim937** [comment]
> I could try to try a different node package, since I have tried with different applications and some of them partially open the file.

From what I saw, Honeyview and 7zip both can see 28 normal images+1 corrupted.
I tested with cbz I sent to you and tried recreate situation from https://github.com/ollm/OpenComic/issues/194#issuecomment-1984732763 and so far there is no app freeze and\or error messages. For situation from comment there is usually long\infinite loading, sometimes it shows that it can't unzip file.

**Comment by ollm** [comment]
Thanks for mentioning that it works in 7zip.

I have changed the default extraction for zip files to 7z d07feac608903ef7ba582273bca06abaded4f4df and now all 28 images are extracted +1 corrupted, it also slightly increases performance in extracion zip files in general.

Build: https://mega.nz/file/rSQjxDZC#KhQjUtQHk6KpZc7xvndzShe9uCsSDx4cEsj218HFYlU

**Comment by ollm** [comment]
Something I forgot to mention is that you may have to delete the cache, since OpenComic will use the previously generated cache when reading the file.

**Comment by dajotim937** [comment]
I usually just create new folder with testN, where N = 1,2,3.... It do the trick with cache.
With cbz file, yeah it shows 28+1 images. And there is error notification about wrong CRC, however I think it should shows every time when corrupted cbz is opened, not only first time.

**Comment by dajotim937** [comment]
While there is notification when you open file, there is also notification every time when you open folder with cbz files, when one cbz is corrupted. The issue is that the message is `Error when unzipping: unknown error.` when you didn't open corrupted file yet and `Error when unzipping: CRC failed : **.jpg` when you opened file once(which means there is cache of file). And when you open folder with cbz files you can't understand which file is corrupted, but notification is showed just when you opened folder, not file.

https://github.com/ollm/OpenComic/assets/96221151/2fb4470a-0f0e-4f21-8ad5-ad1936f4bffe

**Comment by ollm** [comment]
I've improved a little how this is handled, note that once a compressed file has been extracted, the next times it will be accessed from the cache/tmp, currently I save the last error message in the cache to continue showing it, but it does not always work as expected.

Extract corrupt file show first error message: b95de2cf88963975f57512018b3438bbbc89a331
Separate compressed error messages of different files 3d77bb368c599622ffe608b0d70d95bf4d0fe242

Build: https://mega.nz/file/nbQUlDIJ#iVhuBj0ES_H4VUCR0Kl36l980bmSBkYmKKmNpt0anpA

**Comment by dajotim937** [comment]
> but it does not always work as expected.
Current situation for me: error is not shown anymore if I open folder. However, error is shown for each cbz file I have one corrupted cbz, but error is shown for every cbz in folder (UPD: first time it has been shown presumably for every cbz, after clearing cache and tmp it's shown for some unrelated uncorrupted cbz, but isn't for others), and for corrupted cbz (which contains corrupted image) error is shown 2 times.

**Comment by ollm** [comment]
I'm going to reopen this, since I've only tested it with the corrupt file and not alongside other files.

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
