### ISSUE TITLE
[Bug]: Lexicographic sorting of pages inside a manga chapters loads pages out of order

### ISSUE THREAD

**Issue by TyrantRC** [ollm/OpenComic#206]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0

### Operating System

Windows 10 Pro N 22H2 19045.4046

### Steps to reproduce

1. add a comic where the pages are numbered without numbering padding, as in 1.png, 2.png, 3.png, ..., 10.png
2. open comic
3. pass through the pages

### Expected Behavior

OC (as almost every other reader) should organize pages using numerical (key) sorting so that it shows the pages in this order:
1.png, 2.png, 3.png, 4.png, 5.png, 6.png, 7.png, 8.png, 9.png, 10.png

### Actual Behavior

it organizes pages with lexicographic sorting, so it thinks 10 comes before 2, 20 before 3, and so on
![image](https://i.imgur.com/VuFAOmq.jpeg)

### Additional Information

I know this can be fixed by renaming all the pages with numbering padding (001, 002, 003, etc) but not everyone is tech-savvy enough to know how to use a renamer app. This is expected in modern readers, here are some examples of other readers:
Honeyview
![](https://i.imgur.com/Qr7XKNL.jpeg)
Houdoku
![](https://i.imgur.com/NkcyixJ.jpeg)
Kavita
![](https://i.imgur.com/USDZydc.jpeg)
Yomikiru
![](https://i.imgur.com/IM4ZROB.jpeg)

**Comment by ollm** [comment]
It looks like you have sort by name selected, you would need to change to Number or Name / Number to correct this.

![Captura desde 2024-02-22 16-15-38](https://github.com/ollm/OpenComic/assets/18549191/784929ce-7fbc-4710-9350-8da50ac5a005)

**Comment by TyrantRC** [comment]
You are right, for some reason, It didn't connect in my brain that those settings are for the reader as well, I thought it was only for sorting the library.

May I suggest changing the tooltip to something like "Sort files or pages" instead of just "Sort". It really wasn't intuitive for me.

Thanks for responding, your reader is awesome, the best one I've tried from all the popular ones.
