### ISSUE TITLE
[Feature Request]: Autorotate pages to best fit orientation.

### ISSUE THREAD

**Issue by Sachal01** [ollm/OpenComic#207]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Can you please add a toggleable option to autorotate landscape pages so they fit better on the screen. Without this, landscape images (or double pages) appear very small when the monitor orientation is set to portrait.

So far I manually fixed this by rotating each image in paint and then clearing OpenComic's cache.

### Additional Information

This option would, of course, be for systems with rotatable monitors.

### Sample file

Before
![Screenshot (7)](https://github.com/ollm/OpenComic/assets/160229388/b5bb0305-b458-48f0-94af-31e40c180fb6)
After
![Screenshot (6)](https://github.com/ollm/OpenComic/assets/160229388/79d2184e-aab7-46be-9d2d-2f7095bfdc4f)

**Comment by ollm** [comment]
Closed as completed in 20258ff0ebf57d5a8064dec821ce745b7d9242a3 and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
