### ISSUE TITLE
[Bug]: PDF Error

### ISSUE THREAD

**Issue by Withered-Flower-0422** [ollm/OpenComic#210]
### Preflight Checklist

- [x] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0

### Operating System

win11 23h2

### Steps to reproduce

1. Drag a pdf into the window.
2. An error occurred.
3. Each time I click on the `Library` and `Recents`, the error occurs, and I can't delete them.

### Expected Behavior

When a pdf is dragged into the window, give a hint that "The file is not supported".
Or if pdfs are supported, make it work correctly, instead of repeating showing the error.

### Actual Behavior

I mistakenly dragged a pdf into the window, then an error occurred.
![image](https://github.com/ollm/OpenComic/assets/142531691/db065d0f-8dbd-4c29-b110-14a88b9f8764)
After that, each time I click on the `Library` and `Recents`, the error occurs, and I can't delete them.

**Comment by Withered-Flower-0422** [comment]
I've tried the setup version and the portable version.
The setup one has the bug, while the portable one handles pdfs well.

**Comment by ollm** [comment]
OpenComic supports PDF files.

Can you send me the PDF file that is causing the error? oleguer.llopart.mora@gmail.com
Can you also show me the complete error in the console? `Debbug` > `Toogle DevTools`

As a temporary fix, you can rename or move the PDF file that is giving the error in the file explorer, so that OpenComic does not try to open it.

**Comment by Withered-Flower-0422** [comment]
After my debugging, I think I find the problem.
My floder name contains a `#`, which causes this bug.

**Comment by ollm** [comment]
From what I've seen, it's a `pdf.js` bug https://github.com/mozilla/pdf.js/issues/10632

At the moment I have updated `pdf.js` to the latest version and made some corrections to solves the problem with the `#` (56910730d1b0241370565bce787508ba0811b9a9 and 4fda21551a62e2557f6d9536d2747833f0d7cb5e)

This is the build with the fix https://mega.nz/file/3bhyQD5Y#KwmcChEdpy92FUQF2V5MksW6tERzTrsNQHeveLL0FGQ

**Comment by ollm** [comment]
Closed as fix available in [v1.2.0](https://github.com/ollm/OpenComic/releases)
