### ISSUE TITLE
[Bug]: Fail to open the folder in `Master folders` (Escape symbol bug)

### ISSUE THREAD

**Issue by Withered-Flower-0422** [ollm/OpenComic#211]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0

### Operating System

win11 23h2

### Steps to reproduce

1. Add a folder in the `Master folders`.
2. Click the added folder.
![image](https://github.com/ollm/OpenComic/assets/142531691/a0e7f8eb-cc4c-4ba8-a60e-d4d9c3a90982)

### Expected Behavior

Open the folder correctly.

### Actual Behavior

An error occured that said:
Windows can't find the file. Please confirm if the folder name is correct and try again.
![image](https://github.com/ollm/OpenComic/assets/142531691/e36a50cb-9650-41ab-8929-ba373c051af0)

From the error image, seems the folder path is broken. All `\`s disappear. (a escape symbol bug)

### Error message

Windows can't find the file. Please confirm if the folder name is correct and try again.

**Comment by ollm** [comment]
Closed as completed in 224ef57b0fb13b75d5d0b7f4a8b6b2507e963801 and available in [v1.2.0](https://github.com/ollm/OpenComic/releases)
