### ISSUE TITLE
[Bug]: Can't scroll past some position in fullscreen

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#212]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

12.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

From here: https://github.com/ollm/OpenComic/issues/194#issuecomment-1973862391

Can't scroll past some position in fullscreen (F11).
Not webtoon mode (but still vertical), and used custom zoom in (ctrl+mousewheel) without "adjust to width" option. With this option everything's fine even in fullscreen.

https://github.com/ollm/OpenComic/assets/96221151/4a9e0a9b-05cf-4f04-9983-3a497c8381f9

Also sent to email with bigger video.

### Expected Behavior

No difference between fullscreen and regular.

### Actual Behavior

There is.

**Comment by ollm** [comment]
Fixed in 65a447c1ce395214b1f787e5eb0824f003655f11

Build: https://mega.nz/file/nbQUlDIJ#iVhuBj0ES_H4VUCR0Kl36l980bmSBkYmKKmNpt0anpA

**Comment by dajotim937** [comment]
Also can't reproduce anymore.

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
