### ISSUE TITLE
[Feature Request]: Save Images

### ISSUE THREAD

**Issue by Megatro-nn** [ollm/OpenComic#218]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Adding an option to save images while reading and add the file name and page number to the saved image.

**Comment by ollm** [comment]
Closed as completed in 64f7fc9a0f3204effc9ac4243bc360427d4e7663 and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
