### ISSUE TITLE
[Feature Request]: Library Navigation using side mouse buttons

### ISSUE THREAD

**Issue by Sachal01** [ollm/OpenComic#219]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Can you add the ability to navigate forward or backward in the comic library (non-reading mode) using side mouse buttons, similar to how it works in Windows Explorer. It would be a nice QoL change.

**Comment by ollm** [comment]
Closed as completed in 96f4bb8e0033bd58b78e9ec29155ae332c72ec8b and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
