### ISSUE TITLE
Is it possible for a webtoon reader to be implemented here?

### ISSUE THREAD

**Issue by farahnur42** [ollm/OpenComic#22]
Honestly title says it all, can a vertical reader (so pages with small gaps in between in the reader, and you can scroll through the entire chapter/volume at a go if not through consecutive chapters) and/or webtoon (so no gap between the images and it's one big blob) be implemented for this reader?

**Comment by farahnur42** [comment]
Just realized that there is a vertical reader, that being the scroll down mode. So that just leaves the webtoon reader as my request now.

**Comment by ollm** [comment]
I think it is possible to read Webtoons by jointly activating the page scroll and the adjust to width switch. You can also set the margin to 0 or the value you want (Below adjust to width)

If with this you can correctly read webtoons I can add a new switch that activates these options automatically.

I leave some captures.

![](https://i.ibb.co/MVTfgLw/Screenshot-1.png)
![](https://i.ibb.co/tsjYbvh/Screenshot-2.png)
![](https://i.ibb.co/HzzwkCD/Screenshot-3.png)

**Comment by farahnur42** [comment]
Yeah this approach works, I just tested it. The only issue being that scaling is an issue on certain titles so it'd be helpful to have the Webtoons button so to speak only change the margin and not necessarily the width as well, with the width option being available separately. Not sure if I should close this issue until it is implemented tho, but yeah that is an acceptable solution.

**Comment by ollm** [comment]
Do you think there should be a different option for the top/bottom margin and the right/left margin when reading webtoon?

**Comment by farahnur42** [comment]
I think that that would be a worthwhile addition, yes. It'd make fit to height and fit to width both less confusing to boot

**Comment by ollm** [comment]
I have added the new webtoon switch 198038c22c4876bda6aad4f3b215d0b6a5b4071e and separated the horizontal margin from the vertical f006b62749efa14e46bb7b5e4cd1800769119ff5.

When I have a moment I will update the binaries to a new version.

**Comment by farahnur42** [comment]
Thank you very much for your work and I guess I can close this now.
