### ISSUE TITLE
[Feature Request]: An option to disable gamepad input

### ISSUE THREAD

**Issue by MartyMcStarfox** [ollm/OpenComic#220]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

This seems to only a problem with racing wheels, but whenever my G29 is connected to my PC, it forces OpenComic to scroll to the bottom of any page I load (i.e settings, library) before it lets me click anything, so I thought an option to disable gamepad input might fix that. Given that my problem's likely a little niche, OC also seems to listen to controllers when it's not focused, so that may be another reason to add it. (Don't know if I should've put this in bugs or not!)

**Comment by ollm** [comment]
Closed as completed in 5a2285f6d750280584455f55da0249686cecc153 and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
