### ISSUE TITLE
[Feature Request]: Add more than one tap zone

### ISSUE THREAD

**Issue by woducku** [ollm/OpenComic#221]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

In reader, when i tap on the right panel, it should go to previous page. atm it only goes forward. 2 (left and right) should be good enough. 3 can also be nice where middle one can changeable to various functions like history, show both bar or a reader settings etc.

### Sample file

https://github.com/ollm/OpenComic/assets/57977673/905a4819-9ca9-49b9-8e7f-cd25825e1896

**Comment by ollm** [comment]
Closed as completed in c7ee38f2b85d85896bd197a8be4a68abd8bb300f and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
