### ISSUE TITLE
[Bug]: No menu when open

### ISSUE THREAD

**Issue by Antaza** [ollm/OpenComic#222]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.1.0 & 1.2.0

### Operating System

Windows 10 22H2

### Steps to reproduce

1. Open a folder using recent tab. Inside it there are many folders, the only files inside that folder are shortcut folder ".ink" file, bat file for delete .nomedia files, and ps1 (same as bat file for delete .nomedia)
2. Error message pop-up saying can't read some files in app.asar
3. Blank screen with no menus

### Expected Behavior

Try to reopen and hope it back to normal

### Actual Behavior

![image_2024-04-21_111820604](https://github.com/ollm/OpenComic/assets/75477223/8e68d236-4f8f-4fb9-a55d-a058d264fe5b)

### Error message

Uncaught (in promise) ReferenceError: win is not defined
    at fullScreen (opencomic.js:23:2)
    at opencomic.js:527:5
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/Parser.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/Tokenizer.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/decode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/decode-data-html.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/decode-data-xml.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/decode_codepoint.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/stringify.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/encode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/encode-html.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/escape.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/traversal.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/manipulation.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/querying.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/legacy.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/helpers.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not load content for file:///C:/Users/ASUS/AppData/Local/Programs/OpenComic/resources/app.asar/templates/feeds.js.map: Unexpected end of JSON input

### Additional Information

I have tried to reinstall, downgrade from 1.2.0 to 1.1.0, try other build from similar issue on 1.1.0 version, and use portable version but no change

**Comment by ollm** [comment]
Can you check if this fixes the issue? d72813abbb0320a94bee5b2881c2bfcd1f2084cf

Build: https://mega.nz/file/CDRljQhS#ZQIEnAKtgJ0DXu2ow5Wo-ctHNKshudmQg2naWCL6Mes

**Comment by Antaza** [comment]
Sorry for late replied. I tried install what you suggest and it works.
I tried to reopen the app and it run normally
![Untitled](https://github.com/ollm/OpenComic/assets/75477223/415951b1-6b59-47a0-9b4e-17c9c51d32cd)

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
