### ISSUE TITLE
[Feature Request]: Image Transitions

### ISSUE THREAD

**Issue by Laughingcow** [ollm/OpenComic#225]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Is it possible to add image transitions such as page turn and fades? I want to have a proper feel of reading a comic book and having that effect makes a difference. GonVisor has a whole slew of these but is temperamental and doesn't read all file formats.

Another bit is having a SoundFX play during the transition. Honeyview had this before it was removed where a page turning sound would play everytime a page was turned.

**Comment by ollm** [comment]
I'll see if it's possible to do, the fading effect is easy, but the transitions that simulates a page turn may be more complicated.

**Comment by Laughingcow** [comment]
It isn't just the effect itself but the speed on which is goes. Gonvisor has the ability to set the speed on which the transition goes. I have no idea how this works from a technical perspective but it is possible. I highly recommend looking into GonVisor and how it handles all this.
![Screenshot 2024-04-30 085253](https://github.com/ollm/OpenComic/assets/17080533/ff3fbc61-ba1c-460e-ba88-4b0026f851cc)
![Screenshot 2024-04-30 085258](https://github.com/ollm/OpenComic/assets/17080533/d365585d-44df-491d-9aed-52892952d136)
![Screenshot 2024-04-30 085207](https://github.com/ollm/OpenComic/assets/17080533/84909534-b131-4268-a2c1-bddfc5a35f49)

Could help you figure things out.

**Comment by Laughingcow** [comment]
Good to know.

If you can get it to work, the next thing would be getting sounds for the transitions. There's plenty of sounds on youtube and other places.
https://www.youtube.com/watch?v=tAADqtTtT7k

The idea is that during the page transition, you can have it play a small sound cue if you wanted. Again, it helps with the immersion.

**Comment by ollm** [comment]
I will also take it into account for this feature, if there is any other type of sound that you would like there to be when turning the page, you can also send me an example video/audio.

**Comment by Laughingcow** [comment]
Nothing comes to mind but I imagine others might think otherwise. I think a better solution than adding a bunch of sounds is to allow users add custom sounds if they want. That would save you a headache in the long run.
