### ISSUE TITLE
[Bug]: fast pressing 'next chapter' hotkey while current chapter is loading

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#230]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

1. Scroll to end of chapter
2. Press 'next chapter' hotkey fast several times

### Expected Behavior

Chapter opens without any issue

### Actual Behavior

Different errors occur.
![2024-05-15_16-45-46](https://github.com/ollm/OpenComic/assets/96221151/f39b739f-0dd9-4912-bd2f-9cf12fe5b46b)

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
