### ISSUE TITLE
[Bug]: 'Start opencomic in fullscreen' will lead blackscreen and "win is not defined" error

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ollm/OpenComic#233]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

WIN 10 22H2 19045.3324

### Steps to reproduce

1. CLICK 'Start opencomic in full screen' OPTION under startup behavior option group
2. CLOSE  opencomic
3. Open a cbz file with opencomic in "windows open with" method ( So I can open a comic file just with double click in explorer)
![image](https://github.com/ollm/OpenComic/assets/2074641/9086fa91-3c7a-4fed-b36a-0519c08bbeb9)

### Expected Behavior

 Open a cbz file with opencomic in "windows open with" method normally.

### Actual Behavior

Some files will lead black screen (colored background) and for a minute an error box

(Even a very small file)

### Error message

![image](https://github.com/ollm/OpenComic/assets/2074641/3de45063-5977-43f0-a914-8b11b7e38e2f)

### Additional Information

I have used many Electron apps on windows, many of them has problems with full screen black screen bugs if I open a file with "windows open with" method.

**Comment by ollm** [comment]
It seems to be the same bug as https://github.com/ollm/OpenComic/issues/222

You can try the following build of the master branch which includes the following fix d72813abbb0320a94bee5b2881c2bfcd1f2084cf

Build: https://mega.nz/file/vTgjwK5K#cZByTcMcJzn7-h5GHnmlL4niJ157Wo-uHV0XwBRxl4c
