### ISSUE TITLE
[Bug]: (ENOENT) Unable to handle files on web server with pure ip address such as \\192.168.X.X 

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ollm/OpenComic#234]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

WIN 10 22H2 19045.3324

### Steps to reproduce

 Open a file with opencomic on web server such as \192.168.X.X 

### Expected Behavior

Open it normally

### Actual Behavior

Cannot open 

### Error message

![image](https://github.com/ollm/OpenComic/assets/2074641/c147c274-06e2-405b-99d7-eb64d6a628fb)

### Additional Information

If I move the file to local disk ,it could be opened normally

**Comment by ollm** [comment]
What protocol are you using? From the capture it seems that he has not specified it.
Have you configured the server from OpenComic settings? or are you using some other method?

**Comment by ollm** [comment]
> I think in windows we should use \\192.xxxx\folder, and smb:// address format is just for mac and Linux
> But I can only write with smb:// address in your configration of opencomic in WIN os, other format cannot be saved

I don't think this is the cause of the problem, the library used to connect to `smb` servers uses the slash `/` for directories.

I have made some changes to show more detailed error messages when connecting to a server c80bcbc51ed257e4a1a830d9a010cc917741e852
Build: https://mega.nz/file/rWAyAJJA#NIOv9FVVXV14Z1UBkvQbzXtBtUKnppVPUYhQuDTMIQE

---------

You can check if the `smb` server appears in file explorer and if you can connect to it (Only if you have network discovery activated).

![Captura de pantalla 2024-05-27 082841](https://github.com/ollm/OpenComic/assets/18549191/0d3fb221-dd2c-4cb7-9935-b07033b403f2)

Also, make sure that the path is correct, the path must include at least the main folder, if you can access it from the file explorer, in my case it would have to start with the one that is marked, like this `smb://192.168.1.107/Users/Llopart/Pictures/OC Test`

![Captura de pantalla 2024-05-27 083853](https://github.com/ollm/OpenComic/assets/18549191/742e9d76-d357-44da-90b9-1139d60f0e52)

Finally, if the above has not worked, you can check in the console if there are any more errors, and show me a screenshot of them, for example, in this screenshot the `pc/smb` I am trying to access is not connected to the local network.

![Captura de pantalla 2024-05-27 082908](https://github.com/ollm/OpenComic/assets/18549191/8e901b71-1b61-4b26-b3c8-c16c8cd3fd4a)

**Comment by ollm** [comment]
It seems that I have found the cause of the bug, in some places in OpenComic the two backslashes were removed in the path of files share over a network bab197fa11f89ae07a707e4f42ea144a5416f25f

Since you are opening the files from the file explorer, you do not need to configure the server from settings.

Build with fix: https://mega.nz/file/zbx3maAK#UP67deOXFB39shZGfinJgTYjhuH2JRri_v-sVMoBUug
