### ISSUE TITLE
[Feature Request]: lower the memory usage on large archive files

### ISSUE THREAD

**Issue by tw8sqf3s** [ollm/OpenComic#236]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

have some type of setting that limits the number of images or the total size of said images that get loaded into memory.

### Additional Information

loading large cbz files with a lot of images (aka. manga volumes) makes the app take up to a gigabyte of memory which really slows everything down on low end systems.

it takes about 1.2GB of memory when opening then after a minute or two it settles around 650MB ~ 700MB while keeping my HDD pinned at 100%

**Comment by ollm** [comment]
For now, you can try this Windows build of the master branch, it has some performance improvements 0e6000f00e445de98eab7cdfbf72ee9b0016bf26, although the memory usage should be the same, the HDD/CPU usage should be reduced.

Build: https://mega.nz/file/zbx3maAK#UP67deOXFB39shZGfinJgTYjhuH2JRri_v-sVMoBUug

**Comment by ollm** [comment]
Closed as completed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

- Optimized index loading and folder navigation 0e6000f00e445de98eab7cdfbf72ee9b0016bf26
- Improved reading load and memory usage f12cbdbade5e487f5c608e253a6c82b8e7c554a4
