### ISSUE TITLE
[Feature Request]: A web version to avoid multiple browsers

### ISSUE THREAD

**Issue by Mathis-Aubry** [ollm/OpenComic#238]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

I don't know much about what it implies, but I feel like having so many electron apps, each having a different browser is wrong
Takes performances out, and disk space, while my normal browser will always be there anyway

Thank you for your work on OpenComic, it is already a fantastic app I can't work without!

**Comment by ollm** [comment]
I'm sorry, but OpenComic uses some dependencies that only work in nodejs, such as [sharp](https://github.com/lovell/sharp/issues/3320), also the app is designed to work in electron and parts of the code would have to be rewritten.

**Comment by Mathis-Aubry** [comment]
ain't a request meant to need some work anyway, why closing this as completed

**Comment by ollm** [comment]
I closed it as completed by mistake, I have already changed it to `Close as not planned`
