### ISSUE TITLE
[Feature Request]: webdav support

### ISSUE THREAD

**Issue by GeistPrisma** [ollm/OpenComic#239]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

webdav support, streaming reading without downloading cbz files

**Comment by ollm** [comment]
I've added support for webdav b6f4439d8953b3855fbc3d7ff476bfd6230a51a1 Can you test if it works correctly with this build? I haven't been able to test it properly.

Build: https://mega.nz/file/TPxFCZiJ#onc9KoksCtWK7kO3HpwJpaWnS0auLwOR9tNWjf0aUDM

**Comment by GeistPrisma** [comment]
> I've added support for webdav [b6f4439](https://github.com/ollm/OpenComic/commit/b6f4439d8953b3855fbc3d7ff476bfd6230a51a1) Can you test if it works correctly with this build? I haven't been able to test it properly.
> 
> Build: https://mega.nz/file/TPxFCZiJ#onc9KoksCtWK7kO3HpwJpaWnS0auLwOR9tNWjf0aUDM

Thank you for your work. The “webdav:// ”defaults to using HTTPS for server connections and cannot connect to HTTP services, such as those hosted on a local NAS.

**Comment by ollm** [comment]
I've made some changes to support WebDAV without HTTPS dc1e60700e762a55a1c95d911fc22e79c6cd9a30

HTTP: `webdav://`
HTTPS: `webdavs://`

Build: https://mega.nz/file/HHw1yRTZ#ZR1ZHN6Nrhku03YdanzMgxiIQBx4TtSaYxRkpkPZIUU

**Comment by GeistPrisma** [comment]
> I've made some changes to support WebDAV without HTTPS [dc1e607](https://github.com/ollm/OpenComic/commit/dc1e60700e762a55a1c95d911fc22e79c6cd9a30)
> 
> HTTP: `webdav://` HTTPS: `webdavs://`
> 
> Build: https://mega.nz/file/HHw1yRTZ#ZR1ZHN6Nrhku03YdanzMgxiIQBx4TtSaYxRkpkPZIUU

I reviewed the headers, the current "webdav://“ does not support URLs with port, such as 127.0.0.1:1234. Additionally, it seems that username and passwords is not being sent correctly, The same parameters work well with the Windows WebClient.

**Comment by ollm** [comment]
I have fixed the issue where the set port was ignored 09f42f53ab7127ebc4a2b8e64f67ffe195bed6c3 , regarding authentication, I have changed it from `AuthType.Digest` to `AuthType.Auto`, which should have fixed the issue.

Build: https://mega.nz/file/efJEXAJJ#i5VPT3j7J-VE6o-npjxmVz8_L9RGombvhRZ6NxIcamo

**Comment by GeistPrisma** [comment]
> I have fixed the issue where the set port was ignored [09f42f5](https://github.com/ollm/OpenComic/commit/09f42f53ab7127ebc4a2b8e64f67ffe195bed6c3) , regarding authentication, I have changed it from `AuthType.Digest` to `AuthType.Auto`, which should have fixed the issue.
> 
> Build: https://mega.nz/file/efJEXAJJ#i5VPT3j7J-VE6o-npjxmVz8_L9RGombvhRZ6NxIcamo

Now "webdav://" connects to the server correctly. However, when switching to Library label or serve label, OpenComic will auto download all files from the webdav server. "smb://" has the same problem ,the other serves I haven't tested yet. 

About reading from server, I submitted a new issue https://github.com/ollm/OpenComic/issues/260

**Comment by ollm** [comment]
Closed as completed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
