### ISSUE TITLE
[Feature Request]: option to right click and choose to delete the file from location

### ISSUE THREAD

**Issue by Hardik-G1** [ollm/OpenComic#240]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

On right click , the context opens which has the option to delete the file from the folder (not the library but physically delete the file from the drive)

**Comment by ollm** [comment]
Closed as completed in https://github.com/ollm/OpenComic/commit/2737fbe2b9a318c9e5a8b27885e153caa5e9b327 and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
