### ISSUE TITLE
[Feature Request]: Add more keybinds

### ISSUE THREAD

**Issue by Jon-Wesly** [ollm/OpenComic#246]
I used to use MComix (https://sourceforge.net/projects/mcomix/)
and I liked the fact that you could just press W to Fit Width, H to Fit Height, B for Best Fit, etc.
It would be nice if you could also just press S to go straight to settings.
Although not necessary, it would be nice to have such conveniences built into OpenComic.

**Comment by ollm** [comment]
Closed as completed in 9201e1fcf06401e498d3996bb45be314905b0fde and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

Although most of the keybinds you mentioned are not possible in OpenComic, I have added more in the new release.
