### ISSUE TITLE
Cannot display PDF Without Compleatly Messing Up Zoom

### ISSUE THREAD

**Issue by Quest79** [ollm/OpenComic#247]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0 Portable

### Operating System

Windows 11

### Steps to reproduce

Look at video.

Possibly windows scaling settings were not taken into account with this zoom feature? Not sure whats going on. No other app with zoom capabilities ive ever used has had this issue.

### Expected Behavior

It should zoom in and out without doing what its doing. 

This happens in 'reading webtoon' when you zoom in a couple times too. Makes this unusable to read comics manga etc.

### Actual Behavior

Zoom should work properly. As it is not it zooms in and crops off half the document

### Sample file

https://github.com/ollm/OpenComic/assets/635094/f1bd0225-17e3-4d0f-9719-d9f12609bea8
[_Solo Leveling Chapter 5_text.pdf](https://github.com/user-attachments/files/15982791/_Solo.Leveling.Chapter.5_text.pdf)

Another example switching to webtoon mode. Same issue. By the way this pdf works fine in firefox pdf viewer when zoom is used. But i rather use this..

https://github.com/ollm/OpenComic/assets/635094/8799ccbd-69e3-4199-b8b4-ac994e61ec4e

**Comment by ollm** [comment]
It seems to be the same error as https://github.com/ollm/OpenComic/issues/223

You can try this master portable version with the following fix d318cfc071b5e8d919b4c8acef89b85e8ef40cc8

Portable Build: https://mega.nz/file/zbQR0YIZ#WkFLsg3_fSZ5Xt5V-h8L-xb0wdqMXCLsqWZr-UxG-Wo

**Comment by Quest79** [comment]
> It seems to be the same error as #223
> 
> You can try this master portable version with the following fix [d318cfc](https://github.com/ollm/OpenComic/commit/d318cfc071b5e8d919b4c8acef89b85e8ef40cc8)
> 
> Portable Build: https://mega.nz/file/zbQR0YIZ#WkFLsg3_fSZ5Xt5V-h8L-xb0wdqMXCLsqWZr-UxG-Wo

I will test that as well thank you.

By the way I tested 1.1.0 and it doesnt seem to have the same issue.

**Comment by Quest79** [comment]
Looks like you fixed it in this dev build. Awesome
