### ISSUE TITLE
[Feature Request]: Horizontal margin steps

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#248]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

I guess it's more feature request than bug.
I checked only for horizontal margin.
Horizontal margin has weird steps to increase it's number
0-20 - value changes by 2
20-50 - by 4
50-200 - by 5
200+ - by 1.
Shouldn't be more value -- bigger step or something like that? At least 200+ should be also 5px step I guess.

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
