### ISSUE TITLE
Error ao abrir OpenComic no KDE Neon User Edition

### ISSUE THREAD

**Issue by juniorandreucci** [ollm/OpenComic#25]
Error ao abrir o openComic, Gtk-Message: 00:39:55.732: Failed to load module "appmenu-gtk-module"
Obs: tanto nos pacotes .deb quanto os snap apresenta o mesmo erro

**Comment by ollm** [comment]
I am also in KDE Neon User Edition and both the deb and snap versions work for me.

In which version of KDE Neon are you? You can find out with this command `lsb_release -a`

My version is:

```
Distributor ID: neon
Description:    KDE neon User Edition 5.17
Release:        18.04
Codename:       bionic
```
