### ISSUE TITLE
[Bug]: Cannot delete output file : The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by gsxgmpkt9020** [ollm/OpenComic#263]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0.master.7b1bbdf.

### Operating System

WIN 10 22H2 19045.3324

### Steps to reproduce

Open a image of a certain comic.

### Expected Behavior

Open the image successfully without errors.

### Actual Behavior

Open the image successfully with errors.
![image](https://github.com/user-attachments/assets/7a0600d4-02f3-4296-b2b6-8f8e41770ff0)

### Error message

Error when unzipping
```
C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:930 Objectmessage: "Cannot delete output file : The process cannot access the file because it is being used by another process. : C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\opencomic\\29ac2a2684078aff69338cc61071b84e522d7d91\\1197_MIZUHO2.png"[[Prototype]]: Object
compressedError @ C:\Program Files\OpenComic\resources\app.asar\scripts\dom.js:930
```

**Comment by ollm** [comment]
I can't reproduce the bug, it seems that there is some other program using the file, do you have multiple instances of OpenComic open?
