### ISSUE TITLE
[Bug]: error when use with controller 

### ISSUE THREAD

**Issue by ward333611** [ollm/OpenComic#264]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

win 11

### Steps to reproduce

![Untitled](https://github.com/user-attachments/assets/ff471cf2-8d3f-4053-9d98-6172f5f9359f)

### Expected Behavior

error when use with controller 

### Actual Behavior

hh

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
