### ISSUE TITLE
[Bug]: Uncaught 'path'

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#265]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

Couldn't find reliable way to reproduce.
I'm getting this error from time to time. Usually when alt+tab while next chapter is loading.
Maybe the fact that I'm reading manga\manhwa without internet connection also playing some part. Or maybe not. But it started roughly at the same time when I updated OpenComic to one of the test build + began to read without internet connection.

UPD: Looks like the issue is happeping when chapter is images in folder. I didn't get any issue from 150 cbz file, but moments I got into chapter that images in folder I caught this issue 2 times.

### Expected Behavior

-

### Actual Behavior

![2024-09-11_05-50-40](https://github.com/user-attachments/assets/a443639e-cf2c-45c7-b1fd-5a9164b9bd56)

**Comment by ollm** [comment]
I made this change to avoid running the save function while chapter is loading eea0b7c2766575278f40a730d173cef6330a0e1a
Although I'm not 100% sure if this will fix the error.

Build: https://mega.nz/file/WPxXQYaC#fpDIv1iisNnf-o05ryoAl8Q0wyB2gM_-UtP9vGm2cAQ

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)
