### ISSUE TITLE
[Feature Request]: Move zoom using keys

### ISSUE THREAD

**Issue by NaiveProtagonist** [ollm/OpenComic#266]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

When zooming in/out using keys, it only zooms to the center of the image. Having the ability to move this zoom around using keybinds would be convenient. For example, I like to use Q and E to zoom in and out, but being able to move my zoom up and down using W and S.

**Comment by ollm** [comment]
Closed as completed in https://github.com/ollm/OpenComic/commit/9201e1fcf06401e498d3996bb45be314905b0fde and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

I have added the mentioned shortcuts for zoom (Q/E/W/S), but they also can be changed from the settings.
