### ISSUE TITLE
[Bug]: Zip (and CBZ) files fail to unzip on macOS

### ISSUE THREAD

**Issue by brettchalupa** [ollm/OpenComic#269]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

macOS Sonoma 14.6.1

### Steps to reproduce

1. Go to Library
2. Click the +
3. Select **Add file**
4. Select a CBZ file from the desktop to import it

### Expected Behavior

File is imported and can be read

### Actual Behavior

Error when unzipping and comic cannot be read

### Error message

Error when unzipping
spawn /Applications/OpenComic.app/Contents/Resources/app.asar.unpacked/node_modules/7zip-bin/mac/arm64/7za EACCESS

<img width="479" alt="Screenshot 2024-09-16 at 9 13 33 PM" src="https://github.com/user-attachments/assets/e0beb550-deca-4732-9445-586ff0aec556">

When viewing the comic in the library it shows this:

<img width="1078" alt="Screenshot 2024-09-16 at 9 13 37 PM" src="https://github.com/user-attachments/assets/e22349f3-4da1-4b3e-9ce1-8f9dcfa1fd08">

### Additional Information

I downloaded the version from here: https://github.com/ollm/OpenComic/releases/tag/v1.2.0

Happens regardless of the file being named `.zip` or `.cbz`

Different error message than https://github.com/ollm/OpenComic/issues/267

`.rar` files work

### Sample file

I put the first Pepper and Carrot episode in a zip file here for testing:

[Pepper and Carrot 1.zip](https://github.com/user-attachments/files/17021575/Pepper.and.Carrot.1.zip)

**Comment by griffey** [comment]
Seeing exactly the same behavior on the Mac App Store version.

**Comment by brettchalupa** [comment]
I confirmed zips work fine on 1.2.0 on Windows 11.

**Comment by ollm** [comment]
It seems to be a bug in `7zip-bin` https://github.com/develar/7zip-bin/issues/24, the binaries for macOS don't have the correct permissions.

I'll try if it's possible to change them with a npm `prebuild` or `postinstall` script.

**Comment by ollm** [comment]
I have push this fix 91c8d1d798e2b11b3f9d1cfdfe5698774dd00f05, it seems that if `7zip-bin` are installed from github the binary file seems to have the correct permissions, although I have not been able to test it as it only happens on the `arm64` package and I can only test the `x64` package.

[OpenComic-1.2.0.master.91c8d1d-arm64.dmg](https://mega.nz/file/fXYEQCwb#1LCxUzFg3gS7VtYdfUgRqP6Ex8CGkGyi0Yk95zuqCjo)
[OpenComic-1.2.0.master.91c8d1d-arm64.pkg](https://mega.nz/file/zXwHWAKT#l4M2mWKj99dqjyXOefYpIw83qk2S1GeLapx-XpfsZT8)
[OpenComic-1.2.0.master.91c8d1d-arm64-mac.7z](https://mega.nz/file/WfhHBC6Q#ypUaT3WrfzmCDD31dH2kZL0C418pK0XQjiVBREa9Q08)

**Comment by brettchalupa** [comment]
@ollm I tested the arm build you shared and am no longer seeing the reported error, but the files within the zip don't ever load and render. I just see the spinner rotating:

<img width="1624" alt="Screenshot 2024-10-01 at 10 42 59 PM" src="https://github.com/user-attachments/assets/121fa2ce-04de-4868-b9a1-1f8a493a65ef">

Happy to do more testing to help out.

**Comment by brettchalupa** [comment]
Quick follow up, I checked the console logs and see this:

<img width="559" alt="image" src="https://github.com/user-attachments/assets/17d7439d-06e5-47ce-a054-cb4c37c5edab">

```
Uncaught (in promise) 
Error: Could not load the "sharp" module using the darwin-arm64 runtime
Possible solutions:
- Ensure optional dependencies can be installed:
    npm install --include=optional sharp
- Ensure your package manager supports multi-platform installation:
    See https://sharp.pixelplumbing.com/install#cross-platform
- Add platform-specific dependencies:
    npm install --os=darwin --cpu=arm64 sharp
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/Applications/OpenCo…/lib/sharp.js:113:9)
    at Object.<anonymous> (/Applications/OpenCo…/lib/sharp.js:116:3)
    at Module._compile (node:internal/modules/cjs/loader:1373:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1432:10)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:17025)
    at s._load (node:electron/js2c/renderer_init:2:31018)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
```

**Comment by ollm** [comment]
It seems that now the `sharp` binary for `arm64` was missing, since I'm building from `x64` macOS, I have fixed this with `npm install --os=darwin --cpu=arm64 sharp` and added some tests before building that check that all binaries are present and have the correct permissions fecd8295c68a803bedef9a98f88b29c95da97133

By the way, the sample file has corrupted images inside the `__MACOSX` folder and they are the ones that open by default since they are the first images. It seems that these are files generated by macOS [AppleSingle/AppleDouble](https://en.wikipedia.org/wiki/AppleSingle_and_AppleDouble_formats#Usage)

New builds.

[OpenComic-1.2.0.master.b812712-arm64.dmg](https://mega.nz/file/qaRmSASB#k1UIYlxjLbY39ABkPOLHQ316Zx8U1Yp0NBNyUW2DJdc)
[OpenComic-1.2.0.master.b812712-arm64.pkg](https://mega.nz/file/bfAVyDgI#don-5-EAX3zqHUzyMRLOxzxNcr7e5lbrbUDrJ_mPYBU)
[OpenComic-1.2.0.master.b812712-arm64-mac.7z](https://mega.nz/file/OfInwBpI#2LhxIhQSXhCff_CtEFb0GEF21pJXV7nKdz6lMGQm3CM)

**Comment by brettchalupa** [comment]
@ollm I confirmed that provided build is working as expected now with reading zip files, thank you! 👍
