### ISSUE TITLE
[Bug]: Can't read cbr/z when there's "éàçè" kind of chars

### ISSUE THREAD

**Issue by Mathis-Aubry** [ollm/OpenComic#272]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.2.0

### Operating System

w11

### Steps to reproduce

1. Have a cbr/z packed file containing the folder of images with "éàçè" kind of chars in its name
2. Open it

### Expected Behavior

Working ?

### Actual Behavior

I need to repack the archive myself without the special chars

### Error message

The screen is black

**Comment by ollm** [comment]
Thanks for reporting!

It seems to be the same error as https://github.com/ollm/OpenComic/issues/243 and https://github.com/ollm/OpenComic/issues/193#issuecomment-2117840534

It's a problem with UTF8 characters, you can try this master build which includes the following fix 27c863b6a9abd434e8855216100e5f8087ed1e73

Build: https://mega.nz/file/WTo1FRDJ#49VUmqrkLj6SxS3SuuzZxGc4a1J2F1ZvHuxlXtQTEtg

**Comment by ollm** [comment]
Closed as fixed and available in [v1.3.0](https://github.com/ollm/OpenComic/releases)

**Comment by Mathis-Aubry** [comment]
Hey, sorry for late reply I was looking for a moment to test it out, but 1.3.0 released and my problem disappeared using it !
Thank you for your work and help here
