### ISSUE TITLE
[Bug]: Open location

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#278]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a bug report that matches the one I want to file, without success.

### OpenComic Version

1.3.0

### Operating System

Win10, 22H2, build 19045

### Steps to reproduce

For some reasons, File->Open folder location doesn't work. Also, when you save image you can click "Open" on popup message, that also doesn't dork for me. But right click on folder\chapter->Open folder location is working fine.
And there isn't any message in devtools console. 

### Expected Behavior

Open location working fine.

### Actual Behavior

In some cases OpenComic can't open folder location.

**Comment by ollm** [comment]
Thanks for reporting!

I have published a new version [v1.3.1](https://github.com/ollm/OpenComic/releases) with the following fix a4bc25b3005c097a7852a96c8c41fd866b28ed1c

In the previous version I changed how files are opened in the file explorer due a bug I had in Ubuntu and it seems that this has caused it not to work properly in Windows.
