### ISSUE TITLE
Submit the simplified Chinese language pack, adapted to version v1.3.1.

### ISSUE THREAD

**Issue by kofzhanganguo** [ollm/OpenComic#279]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Submit the simplified Chinese language pack, adapted to version v1.3.1.

### Sample file

[zh-hans.json](https://github.com/user-attachments/files/17267015/zh-hans.json)

**Comment by ollm** [comment]
Thanks for your updated translation!

I've push it to the master branch 2d8803f91bb4f0f8f3c2cc803b5f472e4d31fc25
