### ISSUE TITLE
[Feature Request]: ignore horizontal margin for landscape pages

### ISSUE THREAD

**Issue by dajotim937** [ollm/OpenComic#280]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

When I'm reading manga (not webtoon\manhwa), sometimes the quality of the downloaded pages is very good. For the sake of readability, I use a ~240-250 horizontal margin on a 1920x1080 monitor.                This allows me to view most of the page and follow the flow of the manga page with a little bit of scrolling. If I set the view to show the full page, the text usually becomes too small for me to read. 

However, in this situation, the horizontal margin is also applied to landscape pages, making them smaller. An option to ignore the horizontal margin for those pages would give opportunity for better use of the monitor's full width, making the landscape pages easier to see.

**Comment by ollm** [comment]
Hi @dajotim937, this feature is currently available in OpenComic, you can apply a different margin for horizontal images activating the `Different in horizontals` option.

![Captura de pantalla 2024-10-09 061707](https://github.com/user-attachments/assets/91d089f6-159f-4f9e-918b-718b8a39e76a)

**Comment by dajotim937** [comment]
Oh, I see. Thank you. =)
