### ISSUE TITLE
[Feature Request]: Turn pages with mouse scroll wheel (outside of Vertical Reader)

### ISSUE THREAD

**Issue by sabretou** [ollm/OpenComic#281]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Hello, thank you so much for making this! I'm so happy with OpenComic!

Would it be possible to have a setting where you can scroll pages using the mouse wheel, but in Slide Reader, Page Turn, or Fade modes? I am most used to this functionality as someone coming from Calibre Viewer.

Scroll up would flip the pages back, and scroll down would flip the pages forward.

Apologies if this is already possible and I missed the setting somewhere!

**Comment by ollm** [comment]
Hi, Thanks for the suggestion!

I've added it as an option in the app settings f16406851b7adee7609004c95d4a0fec25f2f025, If the option is activated, the zoom with mouse wheel they only work if the Ctrl key is pressed.

If you want to try it, you can install the following master build.

Build: https://mega.nz/file/iK51zSID#KYee68i8S47mT_CfE09ibbpTx5Z3nQ9lQ_c4AufrUnk
