### ISSUE TITLE
[Feature Request]: Preserve position / stay on top when going to the next page while zoomed in

### ISSUE THREAD

**Issue by benedrill** [ollm/OpenComic#294]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

I usually read zoomed in on a page and just scroll from top to bottom (Usually for manga with small text or when I'm using a small monitor). Currently when I go from page to page it automatically positions itself to the center, and I have to scroll up every time. A feature where going to the next page positions itself to the top when using global zoom would be nice. Also, is it possible to add a setting where you can increase the distance when using zoom up/zoom down? Apologies if these already exist in the app and I somehow missed it.

### Additional Information

I am using the portable version of OpenComic for Windows

**Comment by ollm** [comment]
> I usually read zoomed in on a page and just scroll from top to bottom (Usually for manga with small text or when I'm using a small monitor). Currently when I go from page to page it automatically positions itself to the center, and I have to scroll up every time. A feature where going to the next page positions itself to the top when using global zoom would be nice. 

I think it would be best if you used vertical reading for this case, with vertical reading you start at the top of the next page and not in the middle, which is what you are looking for.

> Also, is it possible to add a setting where you can increase the distance when using zoom up/zoom down? Apologies if these already exist in the app and I somehow missed it.

This is currently not possible, but you can achieve a similar result using horizontal margin.

I leave an example video.

https://github.com/user-attachments/assets/dde3367f-beae-4bb2-a118-9aaf6d552e1a

**Comment by benedrill** [comment]
> I think it would be best if you used vertical reading for this case, with vertical reading you start at the top of the next page and not in the middle, which is what you are looking for.

This is a nice workaround, thanks!
