### ISSUE TITLE
Double pages placeholder is too intrusive

### ISSUE THREAD

**Issue by Nekomajin42** [ollm/OpenComic#31]
When using the double page view with odd number pages, the placeholder at the end should be transparent, or at least opaque. It's especially disturbing, when the dark theme is enabled.

**Comment by ollm** [comment]
I have changed the color of the blank page to black in the dark theme 3f3223c9b493f551e627cae849b4f8a20df67e1c

**Comment by ollm** [comment]
I have fix it 8d1a5b741855fd0bae6a7efd9579c7ddecbfd3d1, I probably added it again when I updated the app theme.

This will be available in the next version.
