### ISSUE TITLE
[Feature Request]: Disable the reading-lense

### ISSUE THREAD

**Issue by Marik2805** [ollm/OpenComic#310]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/ollm/OpenComic/issues) for a feature request that matches the one I want to file, without success.

### Describe your suggested feature

Please add the ability to disable the reading-lense function of the reader.

### Additional Information

I do not know whether it's just a user-specific case with my instance of OpenComic, but I seem to not be able to disable it in any way. If there's such option in settings, and I have missed it, please do point it out and I will be very thankful.

**Comment by Marik2805** [comment]
![1](https://github.com/user-attachments/assets/9444f63c-c23b-4368-ad51-b02572069287)

**Comment by ollm** [comment]
Thanks for reporting!

You can disable the lens by pressing the `m` shortcut key or from its menu (It is not in the settings, it is inside the top bar when reading, magnifying glass icon)

![Captura de pantalla 2024-12-22 195139](https://github.com/user-attachments/assets/8e1197e8-2185-4c90-86e6-e5c639d4e190)

**Comment by Marik2805** [comment]
Thanks a lot!
