### ISSUE TITLE
Is there a way to remove top bar and/or side bar in full screen mode?

### ISSUE THREAD

**Issue by Markismus** [ollm/OpenComic#32]
Is there a way to remove the top bar and/or side bar in full screen mode? I can hide them using DOM inspector, but the space is not reclaimed by the comic.

I read that there are shortcuts, however, I can't seem to intuit them.

**Comment by ZIEXED** [comment]
+1 This is important imo, in fullscreen mode it should be hidden [top and side bar] and only appear again when mouse get to the edge

**Comment by ollm** [comment]
Sorry for the delay, I just implemented it in 9fa8658a25166808ad1bf4ea8263b31a066dbd4c

Thanks for the suggestion.
