### ISSUE TITLE
Archlinux package

### ISSUE THREAD

**Issue by Markismus** [ollm/OpenComic#33]
Using debtap I generated (without extra input) the archlinux package and installed and tested it: 
```
debtap -Q opencomic_0.1.5_amd64.deb 
pacman -U opencomic-0.1.5-1-x86_64.pkg.tar.xz
```
Could you add this info to the install list? Or even better, could you add an Archlinux package ( to the AUR)?

**Comment by ollm** [comment]
Currently there user repository managing by @z00rat

https://aur.archlinux.org/packages/opencomic-bin/
