### ISSUE TITLE
Configuring startup behavior

### ISSUE THREAD

**Issue by ZIEXED** [ollm/OpenComic#36]
The current behavior when opening a file is showing a thumbnails of the file in a normal window, I'd like to be able to configure this behavior
#When opening a file start in
1- Thumbnails \ The first page(reading)
2- Fullscreen mode [On\Off]

**Comment by ollm** [comment]
Closed as completed in 78646fe6f4a17be6fc9fd0c940fd97d438c812c1, cf3de6ed737189b53474a30e277245b988ee5d99 and available in [v1.0.0-beta.4](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.
