### ISSUE TITLE
Windows Version automaticially takes over file associations

### ISSUE THREAD

**Issue by ParisGreen** [ollm/OpenComic#39]
This isn't a huge issue, but the way that Opencomic tries to associate itself with every file it can open is a bit inconvenient. Most of my .zip files aren't comic related and having to reset that across multiple formats seems like an unnecessary step.

**Comment by ollm** [comment]
You're right, sometimes it has bothered me too (I use Ubuntu).

I have removed all file associations excluding cbr, cbt, cbz, cb7 and pdf.

b403d14a0ac184bce8160306cb774f6c91fefcf9

Thanks for the advice.
