### ISSUE TITLE
Zoom pages

### ISSUE THREAD

**Issue by Nekomajin42** [ollm/OpenComic#4]
Can you implement a tool to zoom in/out individual pages? The magnifier is a nice feature to tinker with as a coder, but it's quite troublesome for the users.

The `RMB + wheel` combination could be used to zoom in/out, or you could create a slider.

**Comment by ollm** [comment]
Something similar to image viewers? But just zoom in on an image?

I leave a screenshot.

![](https://i.ibb.co/gwTDQY9/Screenshot-20190711-215409.png)

**Comment by Nekomajin42** [comment]
Like in image viewers, or how you zoom pages in a browser.

**Comment by ollm** [comment]
Then I will start to implement it, when it is finished I will launch an update with this new feature and the other reported bugs corrected.

A greeting.

**Comment by ollm** [comment]
It is already implemented in afd1c6563893cd108e98c5b60cd42a4230282fb7

I have also published an update with all the issues fixed.

https://github.com/ollm/OpenComic/releases/tag/v0.1.3

**Comment by Nekomajin42** [comment]
There is no windows installer on the release page.

**Comment by ollm** [comment]
I have updated the release with the updated installer for windows.

Sorry for the delay, but at the time of launching I did not have a computer with windows nearby.
