### ISSUE TITLE
Cover page omit mode for Comic view

### ISSUE THREAD

**Issue by yasuflatland-lf** [ollm/OpenComic#41]
The page combination for a spread page is off by one page due to the cover page is included. It'd be cool if a reader can omit the cover page so that a reader can read with proper spread page combination.

**Comment by ollm** [comment]
How about adding a switch that adds a blank page at first? (In double page options). This way you can activate it or not depending on whether the comic/manga has a cover.

**Comment by yasuflatland-lf** [comment]
@ollm Yeah, sounds good!

**Comment by ollm** [comment]
I just implemented this in 55505a89f774f43bf6e6499e812aca9455cb8214
