### ISSUE TITLE
Can't open cbr file in mac

### ISSUE THREAD

**Issue by Bamwempan1** [ollm/OpenComic#48]
Hello, i try to open a cbr file on mac and i have an error with de unrar command in the /bin/sh folder.

<pre>
Command failed: unrar vt -v "/Users/*/*.cbr"
/bin/sh: unrar: command not found
</pre>

So the first time i install unrar with brew, and continu to not work. I try the command in terminal and it work.

**Comment by ollm** [comment]
Try this version: https://mega.nz/file/nboVHBhQ#1zz7z4CekqIVvFbdDuthq4lC1Q3MxpiPSOwXy18t5ZU

I have included the unrar binary for mac inside the application.
