### ISSUE TITLE
Option to leave page 1 as single page in double page mode

### ISSUE THREAD

**Issue by Cruism** [ollm/OpenComic#50]
Some comic pages that are made to be put next to each other doesn't pair properly as shown below.

![Screenshot from 2020-08-14 13-06-52](https://user-images.githubusercontent.com/69665908/90219061-753d4400-de2f-11ea-880a-3bd13475c46d.png)
![Screenshot from 2020-08-14 13-09-51](https://user-images.githubusercontent.com/69665908/90219067-77070780-de2f-11ea-942b-6bde2dd9b9d0.png)

**Comment by ollm** [comment]
Try updating to version 0.2.0, this version includes the option to add a blank page at the beginning.

![Captura de pantalla de 2020-08-14 09-01-15](https://user-images.githubusercontent.com/18549191/90222767-06e78a00-de0d-11ea-9228-2bca18df6d5a.png)
