### ISSUE TITLE
Single pages and double pages have different variable zoom.

### ISSUE THREAD

**Issue by Shellshock123** [ollm/OpenComic#52]
I really like the fact that this has a horizontal margin. 

My question is it possible for Horizontal margin to be different for double pages.

Like i want the single pages to have 200px horizontal margin but double pages should fit to width

**Comment by ollm** [comment]
Do you mean with "Do not apply to horizontals" activated?

Yes, it could be done.

**Comment by Shellshock123** [comment]
Yes Do not apply to horizontals. thats perfect.

**Comment by Shellshock123** [comment]
Any updates?

**Comment by ollm** [comment]
Sorry for the delay, I've been busy the last few months.

I don't know if I understood what you meant, do you mean this?

![Captura de pantalla de 2020-11-12 15-52-48](https://user-images.githubusercontent.com/18549191/98955807-a1846180-24ff-11eb-8fb0-f5ebb7294610.png)

**Comment by Shellshock123** [comment]
No thats not what i meant. I hope i can show this well

https://cdn.discordapp.com/attachments/587455426979823626/779040244682588210/Untitled.jpg

Basically single pages are only affected by horizontal margin. Double pages are fit to width.

**Comment by ollm** [comment]
Now I have understood.

I have implemented it in b3a8f887aa3bb81e282fa228913fa8b733e8121b 

![ezgif-5-fb837d4ff837](https://user-images.githubusercontent.com/18549191/99903475-f1fc7b80-2cc4-11eb-9c01-517de7ed0f31.gif)

What package do you have installed? I do not plan to update the App soon, if you want I can compile a package for you.

**Comment by Shellshock123** [comment]
Im using the public app. 0.2.0. last done in august 12

Why ask me a question and then close the page though lmao.

But yes if you can truly thank you.

I really love how seamless this app is.

**Comment by ollm** [comment]
> Im using the public app. 0.2.0. last done in august 12

I mean if you use **exe**, **deb**, **rpm**, etc. So that you can package it in the format.

> Why ask me a question and then close the page though lmao.

Sorry, I have closed it when commenting.

**Comment by Shellshock123** [comment]
Yeah im using OpenComic.Setup.0.2.0.exe

i was not aware their were other options lol

**Comment by ollm** [comment]
This is a version with the function implemented.

https://mega.nz/file/fe4S1BrT#2glN18lQ-Bhk1eJ-QWxejMCMqy5v3ENNH0S-hArWRpo
