### ISSUE TITLE
Doesn't work if the filename contains single quotes

### ISSUE THREAD

**Issue by lelinhtinh** [ollm/OpenComic#55]
If the filename contains single quotes (`'`), OpenComic stops at the image list and can't open the reading page.

- ['test.zip](https://github.com/ollm/OpenComic/files/5243185/test.zip)

**Comment by ollm** [comment]
I have tested it on both Windows and Ubuntu and it works fine. What operating system and App version do you use? It is possible that is fixed in the latest version of the App.

**Comment by lelinhtinh** [comment]
OS: Pop!_OS 20.04 LTS x86_64
OpenComic: 0.2.0

**Comment by lelinhtinh** [comment]
Notice single quotes (`'`) before `'test.zip`, it may have been removed during downloading.

**Comment by ollm** [comment]
> Notice single quotes (') before 'test.zip, it may have been removed during downloading.

I added the quote after downloading it.



Could you show what error appears in the console?

In: Debug > Toggle DevTools

![Captura de pantalla de 2020-09-18 15-55-12](https://user-images.githubusercontent.com/18549191/93605719-69611680-f9c7-11ea-9d5b-e7ba2ab25258.png)
Here's a screenshot with the file open.

**Comment by lelinhtinh** [comment]
![image](https://user-images.githubusercontent.com/5460915/93606223-f5883380-f9f1-11ea-8276-9fef3c889b2f.png)
![image](https://user-images.githubusercontent.com/5460915/93606267-05a01300-f9f2-11ea-8d0c-43d1bfa4e7db.png)

**Comment by lelinhtinh** [comment]
![image](https://user-images.githubusercontent.com/5460915/93606780-b4dcea00-f9f2-11ea-8a1d-8b9113fd4510.png)

**Comment by ollm** [comment]
It seems that the error is present only in the list view, I have changed from Grid to List and it has appeared.

While push the fix you can switch to the grid view to fix it.

**Comment by ollm** [comment]
Fixed in 551dfb2ea2fdeb322e963c523041008676277424

What package do you have installed? I do not plan to update the App soon, if you want I can compile a package with the error fixed.

**Comment by lelinhtinh** [comment]
No need to rush, I was changed from Grid to List and temporarily satisfied.
