### ISSUE TITLE
Thank you so much for making this reader! Also: bookmark error in inverted reading mode

### ISSUE THREAD

**Issue by FRRRANKY** [ollm/OpenComic#58]
Hi! First of all, I'd like to thank the creator of this reader; I've used practicly all the comic readers that are out there and the only one that worked for me prevously was CDisplay. The problem? Their interface sucks. So by mere coincidance I found OpenComic and I've got to say it has absolutly everything I've been looking for in a manga reader for ages. So thank you very much for your work!

Here are somethins that need a little fixing though:

- When bookmarking in inverted reading mode, it saves the mirrored page in the list instead. Bookmarking the page 3/100 gets the bookmark in page 97/100 instead. The bookmark symbol keeps working in the original page, but opening the bookmarks lists shows the wrong page in the chapter.

- Also, when bookmarking a page in a comic and the moving (or deleting) the original source, the bookmark stays even though it does nothing, and I can't manually delete that bookmark either. The same happens with the "continue reading" link when opening the main folder and the chapter is not there. I'd say it's better for it to not show at all in those cases.

- Just as an improvement: I'd like to set permanently the interface zoom, it resets everytime that I open the app and it's somewhat annoying.

- Having access to a reading history would help a lot as well, I usually jump a lot between comics when reading. It's the only feature that I miss from CDisplay.

Really great job with the program and have a nice christmas holidays!

**Comment by ollm** [comment]
Hi, thanks to you also for using it.

> When bookmarking in inverted reading mode, it saves the mirrored page in the list instead. Bookmarking the page 3/100 gets the bookmark in page 97/100 instead. The bookmark symbol keeps working in the original page, but opening the bookmarks lists shows the wrong page in the chapter.
> 
> Also, when bookmarking a page in a comic and the moving (or deleting) the original source, the bookmark stays even though it does nothing, and I can't manually delete that bookmark either. The same happens with the "continue reading" link when opening the main folder and the chapter is not there. I'd say it's better for it to not show at all in those cases.

I will try to fix these errors in the next days / weeks.

> Just as an improvement: I'd like to set permanently the interface zoom, it resets everytime that I open the app and it's somewhat annoying.

I just implemented it in e4c81640d346dc4238064c74dac87bb0476e0d3d

> Having access to a reading history would help a lot as well, I usually jump a lot between comics when reading. It's the only feature that I miss from CDisplay.

Like "File > Recently opened > File/Folders list"? At the moment you can sort the main page by "Last reading".

Happy holidays to you.

**Comment by FRRRANKY** [comment]
Hi! Thank you for your answer!

"File > Recently opened > File/Folders list" would work perfectly well, but having such a nice interface I was thinking in someting like a new "reciently opened" tab below "comics" and showing the folders with their thumbnails in (last opened) date order.

Also, I completely forgot, but it would be totally awesome having a way to tag our own folders in the library just to classify them in genres for example. Some quicks thoughs in ways to show the tagged folders:

- Having a search bar at the home app (I have no idea how hard would that be) and showing the result in the main page.
- Adding yet another tab with the drop-down tags the user has created and showing the tagged folders and their thumbnails once clicked. This is the one I like the most.
- If we could create independent folders on the home and add the folders there, that could work as well. With that you could create multiple ways to open the same folder. Probably the slowest way to do it.

Again, thank you so much for your quick response and keep up the good work!

**Comment by ollm** [comment]
> When bookmarking in inverted reading mode, it saves the mirrored page in the list instead. Bookmarking the page 3/100 gets the bookmark in page 97/100 instead. The bookmark symbol keeps working in the original page, but opening the bookmarks lists shows the wrong page in the chapter.
> 
> Also, when bookmarking a page in a comic and the moving (or deleting) the original source, the bookmark stays even though it does nothing, and I can't manually delete that bookmark either. The same happens with the "continue reading" link when opening the main folder and the chapter is not there. I'd say it's better for it to not show at all in those cases.

I have already fixed the first error here bb42b7a98db5e7406f3b53a2355709965ec375c3, the second I will try to correct it soon.

> "File > Recently opened > File/Folders list" would work perfectly well, but having such a nice interface I was thinking in someting like a new "reciently opened" tab below "comics" and showing the folders with their thumbnails in (last opened) date order.

This is a better way to do it, although I'll probably add both ways to access "Recently opened".

> Also, I completely forgot, but it would be totally awesome having a way to tag our own folders in the library just to classify them in genres for example. Some quicks thoughs in ways to show the tagged folders:
> 
> Having a search bar at the home app (I have no idea how hard would that be) and showing the result in the main page.
> Adding yet another tab with the drop-down tags the user has created and showing the tagged folders and their thumbnails once clicked. This is the one I like the most.
> If we could create independent folders on the home and add the folders there, that could work as well. With that you could create multiple ways to open the same folder. Probably the slowest way to do it.

It's a good idea, but this would take more time, so I leave it for future improvements for now.

**Comment by ollm** [comment]
I'm closing this for now.

Most of these features are now available in the latest beta version [v1.0.0-beta.4](https://github.com/ollm/OpenComic/releases/)

- Recently opened page d2f30653f506993a45e49ad5e7e5e8434c33a9be
- Search and filter in library/browsing 8393903117981bea2b8a79e2e50b77d02334aa05

If you still want any of the other functions there will be a new issue for each of them.

Feel free to comment if you find any bugs.
