### ISSUE TITLE
A couple of feature requests

### ISSUE THREAD

**Issue by hopto-dot** [ollm/OpenComic#59]
### Allow putting next notes on the page
I'm a language learning and this would extremely helpful, this is the best comic reader I've ever tried and this would make the program insanely good. I understand this idea will be rejected, it is a comic reader after all
### Allow picking your own thumbnail for a folder
This would make sure most of the folders I have aren't blank.

## This is a brilliant program, keep it up 👍!

**Comment by ollm** [comment]
> Allow putting next notes on the page

As you mentioned, this is not the main function of OpenComic, although I do not rule out that it will be implemented in the future.

> Allow picking your own thumbnail for a folder


I have added the function for future improvements: https://github.com/ollm/OpenComic/projects/1#card-51748085
