### ISSUE TITLE
Next/previous chapter scroll

### ISSUE THREAD

**Issue by Riztard** [ollm/OpenComic#60]
add next/previous chapter button, and maybe it will be triggered when you try to scroll and hit the bottom

**Comment by ollm** [comment]
Currently this is already implemented, but only in the folders that are added within OpenComic in this way:

```
Comic ->
      -> Chapter 1
      -> Chapter 2
```

You mean this will work on any open folder?

**Comment by Riztard** [comment]
> Currently this is already implemented, but only in the folders that are added within OpenComic in this way

but you need to right-click instead of normal scroll if using vertical mode
and you cant go to next chapter if youre in the middle of pages(need to go to last page)

**Comment by ollm** [comment]
> but you need to right-click, instead of normal scroll if using vertical mode

Yes, this is something that needs to be fix.

> and you cant go to next chapter if youre in the middle of pages(need to go to last page)

For this you only have to press the "Last page" button twice to go to the next chapter.

**Comment by Riztard** [comment]
> For this you only have to press the "Last page" button twice to go to the next chapter.

add direct shortcut maybe if possible? 
and maybe someway so people can tell/would know if you can press that twice

**Comment by ollm** [comment]
> add direct shortcut maybe if possible?

Yes, but currently there are many buttons on the bar, and I do not think it is convenient to add one new with a functionality similar to "Last page".

> and maybe someway so people can tell/would know if you can press that twice

What do you think of a better description of the text that appears when hovering over the button? Ho you have another idea for this.

**Comment by Riztard** [comment]
> Yes, but currently there are many buttons on the bar

true
> What do you think of a better description of the text that appears when hovering over the button? Ho you have another idea for this.

maybe if we already on last page, change this text and button (color/icon)

![image](https://user-images.githubusercontent.com/16263232/103099525-61a5b380-4641-11eb-8f03-189181e6fd45.png)

or maybe add here something like. Next chapter End x2
![image](https://user-images.githubusercontent.com/16263232/103099706-235cc400-4642-11eb-9d53-c324be49eb0c.png)

not sure too, if some pop up every press last/first would be annoying

**Comment by ollm** [comment]
> maybe if we already on last page, change this text and button (color/icon)
> 
> ![image](https://user-images.githubusercontent.com/16263232/103099525-61a5b380-4641-11eb-8f03-189181e6fd45.png)

What do you think of changing the icon and the text for this when it is to the last page:

![Captura de pantalla](https://user-images.githubusercontent.com/18549191/103100524-458b1d80-4613-11eb-8d35-224ab9220fe5.png)

> or maybe add here something like. Next chapter End x2
> ![image](https://user-images.githubusercontent.com/16263232/103099706-235cc400-4642-11eb-9d53-c324be49eb0c.png)

This is also a good idea, since in the menus there is no problem of space, also can add a "Prev chapter" button.

**Comment by Riztard** [comment]
> What do you think of changing the icon and the text for this when it is to the last page:
> 
> ![Captura de pantalla](https://user-images.githubusercontent.com/18549191/103100524-458b1d80-4613-11eb-8d35-224ab9220fe5.png)

that would work
