### ISSUE TITLE
copyright year

### ISSUE THREAD

**Issue by Riztard** [ollm/OpenComic#61]
change the year? or is it intentional?

![image](https://user-images.githubusercontent.com/16263232/103098553-bf380100-463d-11eb-9572-6a4e7b75e984.png)

**Comment by ollm** [comment]
The year is already updated in the repository, it will appear updated in the next version.

https://github.com/ollm/OpenComic/blob/bb42b7a98db5e7406f3b53a2355709965ec375c3/templates/about.body.html#L128
