### ISSUE TITLE
Manga cannot be opened after a specific time period

### ISSUE THREAD

**Issue by FateXBlood** [ollm/OpenComic#62]
1. Add a manga folder in the Library
2. The manga opens easily in the reader
3. Leave the manga there for a month or two
4. Open Comic starts showing a message that the file is no longer compatible even though it worked previously
![image](https://user-images.githubusercontent.com/30192697/103285627-c88ee800-4a06-11eb-807e-4ac122e5fd30.png)

**Solution?**
Could be a cache problem or there is some sort of timer that automatically disables accessing the manga after a month or more period.

**Comment by ollm** [comment]
It seems like a problem with temporary files and cache.

The problem persist when restarting the PC and OpenComic?

**Comment by FateXBlood** [comment]
Yeah, the problem is still there. 
I restarted as well as redownloaded OpenComic from here but didn't help.

**Comment by ollm** [comment]
Is there an error in the developer console when you open the cbr file? Debug > Toggle DevTools

**Comment by FateXBlood** [comment]
Really sorry for the late reply. 

Here's a screenshot.
![image](https://user-images.githubusercontent.com/30192697/103655710-bb867180-4f8f-11eb-8a69-a598e6cc7a17.png)

**Comment by ollm** [comment]
When OpenComic opens a compressed file (rar, cbr, zip, cbz, pdf ...) they are first decompressed in this temporary folder and the images are accessed from there.

I thought that in all operating systems this folder was deleted when restarting the PC (As it happens to me in Ubuntu), but from what I have been reading, some only delete old files, if the files are deleted but not the folders, OpenComic will open an empty folder.

https://en.wikipedia.org/wiki/Temporary_folder

I will have to make OpenComic delete these files when it closes to avoid these open and space errors.

**Comment by FateXBlood** [comment]
I see. I guess there will be a new update regarding this?

**Comment by ollm** [comment]
I just implemented it 8ae17bec7d0f85a1e37abfcf2079784303c35358

You use Windows? Or some other operating system? I do not plan to update the App soon, if you want I can compile a package for you can update OpenComic

**Comment by FateXBlood** [comment]
I use Windows 10. 

Sure, if it's not too much work I'd like to have it. Will it work if I install the package without uninstalling OC first?

**Comment by ollm** [comment]
> Sure, if it's not too much work I'd like to have it. Will it work if I install the package without uninstalling OC first?

Yes, you just have to install it and it will replace the previous version keeping the settings.

https://mega.nz/file/2CJHmYTL#F_gmSenUWU1QTw-Dzc6Sr2laZJ-LvSwfUY3BYW-FJOY

**Comment by FateXBlood** [comment]
When I installed it, this showed up 
![image](https://user-images.githubusercontent.com/30192697/103906816-86f9ed80-5128-11eb-85ed-346522cea48a.png)

And it showed up again when I tried to close OC. Looks like an error.

**Comment by ollm** [comment]
Try this version, the error should no longer appear.

2cec1be51f5edb51aeb31c79459841d27cd24d3f https://mega.nz/file/uOZhCKxK#aSMOrTv1p8WUm75Op4sY1DCd4pLNreVuTnCYpbV7LWc

**Comment by FateXBlood** [comment]
I installed it but this error came up again when I tried to close OC.
![image](https://user-images.githubusercontent.com/30192697/104039496-8d5a9900-51fe-11eb-8cfc-e0b9645e2a12.png)

**Comment by FateXBlood** [comment]
Also, the thumbnails seem to have stopped showing with this Beta.
![image](https://user-images.githubusercontent.com/30192697/104093096-72e0f800-52b0-11eb-85d0-a4aaa949dbd1.png)

**Comment by ollm** [comment]
For now this ad435d08a6e592b3504727f7b3b8d4d26ecab339 should correct the EBUSY error.

The thumbnail error I have to check why it happens. Although you can temporarily fix it by opening the folders of the comics that have the problem.
