### ISSUE TITLE
Enable continuous scrolling when holding up/down button.

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#63]
Right now you have to repeatedly hit up/down button. Holding them does nothing.
Plus when you open a chapter you have to click on the image to even enable any scrolling with keyboard at all (you have to focus into the window).

Also if possible not only adding a continuous scroll on holding keys bot also smooth scrolling with large jumps, like on windows in chrome (when you enable smooth scrolling in chrome).

This is all on 2.0.0 on macOS.

**Comment by ollm** [comment]
It works fine for me.

Do you have the same problem using the left/right arrow keys to scroll?
