### ISSUE TITLE
Bug, invalid signature: 0xafbc7a37 when opening certain cbz archive

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#65]
This is on v. 2.0.0 on macOS.

No problem opening it in other apps like Simple Comic.

**Comment by ollm** [comment]
The file is compressed with 7zip and when trying to unzip it as zip it gives an error.

I push a solution to this error in df03e0a823c9e4b9fc40a7541b76bad01c7be4f2

https://github.com/ollm/OpenComic/blob/df03e0a823c9e4b9fc40a7541b76bad01c7be4f2/scripts/file-compressed.js#L152-L155
