### ISSUE TITLE
Frameless window

### ISSUE THREAD

**Issue by NomarCub** [ollm/OpenComic#66]
Using Electron Frameless Windows you could hide the unnecessary title bar on Windows and other OSes that clashes with app's style and takes up space on screen.

**Comment by NomarCub** [comment]
I know about fullscreen. You'd need to remake the buttons in your own top bar unfortunately. There are many programs that do this.

**Comment by ollm** [comment]
Closed as completed in 9c7346cb37fe3c7aed9200d49e27ed4c5bdbfc96 and available in [v1.0.0-beta.4](https://github.com/ollm/OpenComic/releases)

Feel free to comment if you find any bugs.

**Comment by NomarCub** [comment]
It works well, and is nicely themed, thank you!
