### ISSUE TITLE
Persistent/global zoom + view „fit“ options

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#69]
Now the zoom only works on single 1 page / 2 page view. An option to have persitent zoom would be great (with settings how large steps it should have).

Also if we’re on it, more view/fit/zoom options available would be great, especially if you want to read in a „webtoon“ like mode.

Inspiration for that would be https://github.com/luejerry/html-mangareader
His demo shows all the most used zoom/fit options.

Original size/shrink to fit/shrink width to fit/shrink height to fit/fit to width/smart fit small/smart fit large 

These „fit“ options + global zoom would enable for precise zoom ins/fits, especially if you want to read single page + infinte scroll (the „webtoon“ mode).

Also seperate option to "collapse vertical spacing" is sorely needed for reading webtoons.

**Comment by ollm** [comment]
Closed as completed in c94ac75d5f247a1f423b4192d1b1cab2c066be6f and available in [v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3)

Feel free to comment if you find any bugs.
