### ISSUE TITLE
Button to „refresh" folder to force looking for new files.

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#72]
A button in the folder view to refresh folder (force the app to look again in the folder and add new files) would be awesome.

Currently you have to remove & add again folder if any new files are added so the app would show them.

Also I’m talking about only adding new files, it should not readd files already loaded (that would mean losing progress, needless reloading, and unwanted behavior).

**Comment by ollm** [comment]
Closed as completed in 31675a5a8334abedc056a09a5107f718dc5304e0

Feel free to reopen the issue if you find any bugs.
