### ISSUE TITLE
Independent app-global sensitive brightness slider.

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#75]
Would be great to tame the white pages.

Though it would have to work in the whole app (not only per chapter setting) and it would have to be extremely sensitive slider (since reducing brightness by half, isn’t actually reducing it by half, it’s more).

**Comment by ollm** [comment]
Closed as completed in 04b1caa5d28a468df6e94893bd943518da762030 and available in [v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3)

I have implemented this in the page layout configuration, If you want to configure it globally you will have to edit the "Global configuration"

Feel free to comment if you find any bugs.
