### ISSUE TITLE
More sensitive hidden header bar.

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#77]
Currently I have to move the mouse too close to the top of the window, and that sometimes causes me to move the mouse too close to the top and triggers showing the menu bar (which is hidden in full screen mode) on macOS.

A more sensitive header bar that would have bit taller trigger area would be much appriciated.

**Comment by ollm** [comment]
Closed as completed in 27f63ecf8a2955dbf4971409235c1acd161eb6b3 and available in [v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3)

Feel free to comment if you find any bugs.
