### ISSUE TITLE
Viability of colorization + display options?

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#81]
Akin to ViMangaReader:

![vimr-colorized-reader](https://user-images.githubusercontent.com/8696531/103686304-e58b6400-4f8e-11eb-9c5c-d7a9ae20490c.jpg)

![image](https://user-images.githubusercontent.com/8696531/103686334-f3d98000-4f8e-11eb-8b01-c5ac0ca7222a.jpg)

**Comment by Shellshock123** [comment]
There is a comic reader with an auto color mode dafuq?

**Comment by MarkJeronimus** [comment]
I looks like it just applies a naive color gradient (black→Blue→red→yellow→white, unequal distances) to the grayscales.

**Comment by ollm** [comment]
Closed as completed in 04b1caa5d28a468df6e94893bd943518da762030 and available in [v1.0.0-beta.3](https://github.com/ollm/OpenComic/releases/tag/v1.0.0-beta.3)

The colonization function and adjustments for saturation, brightness, sepia, etc are now available in the beta version of the app.

Apart from having some default preset colors, it is possible to create custom colors, setting the color of the different parts of the gradient, also it is possible to obtain them automatically from an image.

Currently there are few presets, If you create something different that you think should be added, show it here and if I like it I will add it in the next version.

### Example 1

![colonization-1](https://github.com/ollm/OpenComic/assets/18549191/c190e60c-4852-4b08-9f03-d63fb2b3720a)

### Example 2

![colonization-2](https://github.com/ollm/OpenComic/assets/18549191/c9c2290f-9bd3-493e-a69e-c72a4c677ebc)

### Colonization menu

![colonization-3](https://github.com/ollm/OpenComic/assets/18549191/24171727-070d-4c62-b045-2f156111b4d8)

Feel free also to comment if you find any bugs.
