### ISSUE TITLE
Config at linenumber 315:18

### ISSUE THREAD

**Issue by Rapidasher** [ollm/OpenComic#87]
#54
After installing both the debug and "fixed" setups, I still can't use the application at all. Now I'm getting this error message
![error](https://user-images.githubusercontent.com/79699537/109296698-70733700-7839-11eb-9c46-2f984f60cb5d.PNG)
Please help me

**Comment by ollm** [comment]
This should be resolved here 0f490469921d5620820f79fbb0da1f2512a2a8d9 and here 2678152e132420d0b4f701f022c8689c4ecb1d90

Here's a beta version with these changes applied https://mega.nz/file/mWxFzYzJ#1OvulZjQVs6N2ZLWsyO_ZHbM2CpQibvVgrkGQKTgP34

**Comment by Rapidasher** [comment]
Installed and got the same error.
Uninstalled, then reinstalled, same error

**Comment by Rapidasher** [comment]
now it says 324:18

**Comment by ollm** [comment]
This should correct it 68908f27b4835058c28e163805a48c54cdf1bcfa

https://mega.nz/file/nGxFBQoS#DiIHAUxp5SSBvz742TnXqSD0KXeWqJ46e3ege0y9ghw

**Comment by Rapidasher** [comment]
100% working, thank you!

**Comment by Rapidasher** [comment]
100% working, thank you!
