### ISSUE TITLE
A way to move folders

### ISSUE THREAD

**Issue by MarkJeronimus** [ollm/OpenComic#95]
I request a way to move a comic folder to another folder, from within the app.

I could see several ways this could be implemented. Either right-click on a chapter folder and choose "move to..." and it shows a simple 'directory chooser', perhaps only showing the added folders and subfolders.

Alternatively, you could show a tree structure in the left pane (where the "Comics" and "Language" buttons reside, along with a huge unused area) and drag a folder from the main folder view to a folder at the left.

**Comment by ollm** [comment]
I don't think this feature is necessary, currently in the [v1.0.0-beta.4](https://github.com/ollm/OpenComic/releases/) you can open folders/files in file explorer and add master folders to OpenComic.

- Open file location in context menu 339bcc0b21eab52228b7762c92c993d06489aa48
- Master folder support from settings 9edd70ec871855cf2b43fa5cebea4bdf83baae7f

With these functions you should be able to move folders from the file explorer.
