### ISSUE TITLE
Adjustments & fixes  to margin settings. (minimal work)

### ISSUE THREAD

**Issue by frykauf** [ollm/OpenComic#97]
Adjustment:
I want to be able to set margin values to whatever I want (above 200), maybe up to 2000 or even higher.

By setting horizontal margin in high values + the setting of reading webtoons gives you option to fine tune the size -> basically working as a reverse zoom for vertical reading view.
So I want the ability to set 600, 800 or even higher for some scans.

Fix:
Setting vertical margin to zero still shows very thin line -> it should show no line.
(it might be a shadow from next image)

**Comment by adrix89** [comment]
For now as Temporary Fix you can Hack your way to Victory.
Open the Dev Tools(Ctrl+Shift+I)
Use the element selection and select the Horizontal Margin Slider, and set the max="200" to something else.
Slide it to the value you want and that will be saved.

**Comment by ollm** [comment]
You can use this in Dev Tools `storage.updateVar('config', 'readingMaxMargin', 2000);` the value will remain even if you restart the App.

In the future I have thought that this can be set from a settings page in the App.

**Comment by ollm** [comment]
Implemented it in f2de2d26ef55ed0f4b9146caefc89e590198b403
